### ISSUE TITLE
用了CBAM提升有多大呢

### ISSUE THREAD

**Issue by deep-practice** [argusswift/YOLOv4-pytorch#10]

**Comment by argusswift** [comment]
> _No description provided._

在VOC数据集上提升了大约2个点，COCO数据集上没有试验过。你可以试一下。

**Comment by Alex-afka** [comment]
i have a question . where to add cbam model  in yolov4 ？

**Comment by Alex-afka** [comment]
> > _没有提供描述。_
> 
> 在VOC数据集上提升了大约2个点，COCO数据集上没有试验过。你可以试一下。

i have a question . where to add cbam model in yolov4 ？

**Comment by sakurasakura1996** [comment]
> > _No description provided._
> 
> 在VOC数据集上提升了大约2个点，COCO数据集上没有试验过。你可以试一下。
你好，你能提供一下在VOC数据集上预训练的weights文件吗，十分感谢。
