### ISSUE TITLE
How to use the backbone of Mobilenet in this projects? where?

### ISSUE THREAD

**Issue by LeeBinshan** [argusswift/YOLOv4-pytorch#11]
请问在你这个项目里，你是用mobilent 的backbone替换的原本pytorch的darknet吗?
若果是的话，你是怎么做的？

**Comment by argusswift** [comment]
> 请问在你这个项目里，你是用mobilent 的backbone替换的原本pytorch的darknet吗?
> 若果是的话，你是怎么做的？

是的哈，用mobilenet替换darknet。是参考了mobilenet-SSD和mobilenet-yolo的代码。
