### ISSUE TITLE
找不到测试集xml

### ISSUE THREAD

**Issue by kuaileyuandi** [argusswift/YOLOv4-pytorch#114]
![UL3O_X_V1)DVUTH`8VJSYK3](https://user-images.githubusercontent.com/56589047/102789741-81d63800-43df-11eb-9c14-ecf6b0036fc1.png)
![UL3O_X_V1)DVUTH`8VJSYK3](https://user-images.githubusercontent.com/56589047/102789798-94507180-43df-11eb-9fcf-b2d39d7304a0.png)
第一轮训练结束，一直报错，一直找不到xml文件，不知道为什莫

**Comment by argusswift** [comment]
> ![UL3O_X_V1)DVUTH8VJSYK3](https://user-images.githubusercontent.com/56589047/102789741-81d63800-43df-11eb-9c14-ecf6b0036fc1.png) ![UL3O_X_V1)DVUTH8VJSYK3](https://user-images.githubusercontent.com/56589047/102789798-94507180-43df-11eb-9fcf-b2d39d7304a0.png)
> 第一轮训练结束，一直报错，一直找不到xml文件，不知道为什莫

windows or linux?

**Comment by zeven11** [comment]
同样的问题是UBUNTU
