### ISSUE TITLE
# problem with params 

### ISSUE THREAD

**Issue by QQANG** [argusswift/YOLOv4-pytorch#118]
The mobilenetv2-yolov4 model parameter calculated by Python ModelSip.py is params: 185.37m, which is larger than your 
 46.34M.   What is the reason?

**Comment by argusswift** [comment]
> The mobilenetv2-yolov4 model parameter calculated by Python ModelSip.py is params: 185.37m, which is larger than your
> 46.34M. What is the reason?

I only evaluate the params of backbone part, not all model

**Comment by QQANG** [comment]
> > The mobilenetv2-yolov4 model parameter calculated by Python ModelSip.py is params: 185.37m, which is larger than your
> > 46.34M. What is the reason?
> 
> I only evaluate the params of backbone part, not all model
I see,thank you
