### ISSUE TITLE
在运行train.py文件时报错：FileNotFoundError：train_annotation.txt'

### ISSUE THREAD

**Issue by shuang1204** [argusswift/YOLOv4-pytorch#119]
各位有遇到这个问题的吗，train_annotation.txt是从哪里下载或是如何生成的呢？ @argusswift

**Comment by fangdaoyou** [comment]
> 各位有遇到这个问题的吗，train_annotation.txt是从哪里下载或是如何生成的呢？ @argusswift

请问您是如何解决的呢

**Comment by Yolanda2020** [comment]
请问您是怎么解决的这个问题?我也遇到了同样的问题

**Comment by Yolanda2020** [comment]
运行voc.py会生成该文件。
