### ISSUE TITLE
从coco到voc  总是会缺少文件

### ISSUE THREAD

**Issue by Zongwei996** [argusswift/YOLOv4-pytorch#12]
5000张图，只产生了4952个xml，请问问题出来哪里呢，谢谢

**Comment by argusswift** [comment]
> 5000张图，只产生了4952个xml，请问问题出来哪里呢，谢谢

似乎是你json文件出了问题，你可以检查一下.json文件里是否有5000张图片的标注信息。我自己用这个脚本转换都没有问题

**Comment by skyfallsss** [comment]
请问有没有反过来的脚本呢，xml2json的
