### ISSUE TITLE
关于注意力机制的问题

### ISSUE THREAD

**Issue by joe660** [argusswift/YOLOv4-pytorch#120]
作者您好  可以问您个问题吗？  为什么我使用了注意力机制   反而比原模型稍微降低了一些，不知道怎么回事。我用的自己的数据集，也挺大了4000张。

**Comment by argusswift** [comment]
> 作者您好 可以问您个问题吗？ 为什么我使用了注意力机制 反而比原模型稍微降低了一些，不知道怎么回事。我用的自己的数据集，也挺大了4000张。

是在残差模块中用注意力吗
