### ISSUE TITLE
Why the calculation result is NAN

### ISSUE THREAD

**Issue by kuaileyuandi** [argusswift/YOLOv4-pytorch#124]
![image](https://user-images.githubusercontent.com/56589047/103842855-b7626d00-50d1-11eb-8706-83fe4e2dceee.png)
Why the calculation result is NAN？

**Comment by jingtianyilong** [comment]
lr problem. might be too large.

**Comment by argusswift** [comment]
> ![image](https://user-images.githubusercontent.com/56589047/103842855-b7626d00-50d1-11eb-8706-83fe4e2dceee.png)
> Why the calculation result is NAN？

,set LR correctly. check categories. whether your GT matches the picture.
