### ISSUE TITLE
关于    evaluator文件：  self.inference_time = 1.0 * self.inference_time / len(img_inds)               #

### ISSUE THREAD

**Issue by kuaileyuandi** [argusswift/YOLOv4-pytorch#126]
![AL(WSFTQ(X1RAA30{%}XH2B](https://user-images.githubusercontent.com/56589047/103869713-a92e4400-5105-11eb-8d9b-cc84dc5a12d6.png)
![G0MH_OU1BHB%)E5Q 3_DFNX](https://user-images.githubusercontent.com/56589047/103869728-ae8b8e80-5105-11eb-8494-a42abe4026d9.png)
 大家好，请问一下，训练完一轮后，报这个错。
![KM(C @JDNHQ ~H $PQFD@3C](https://user-images.githubusercontent.com/56589047/103869772-be0ad780-5105-11eb-8b11-d230c95fe8d6.png)

**Comment by jingtianyilong** [comment]
check your `img_inds`
and also according to 
```
        img_inds_file = os.path.join(
            self.val_data_path, "ImageSets", "Main", "test.txt"
        )
        with open(img_inds_file, "r") as f:
            lines = f.readlines()
            img_inds = [line.strip() for line in lines]
```
pls also check `test.txt`
