### ISSUE TITLE
#训练Mobilenetv3-YOLOv4

### ISSUE THREAD

**Issue by lilangyi** [argusswift/YOLOv4-pytorch#128]
如果我想训练的模型是MODEL_TYPE = { "TYPE": "Mobilenetv3-YOLOv4" }
下载好了yolov4.weight和mobilenetv3.pth 两个权重文件放在了根目录的weight文件夹下，那我应该如何执行我的训练指令？
是CUDA_VISIBLE_DEVICES=0 nohup python -u train.py  --weight_path weight/yolov4.weights --gpu_id 0 > nohup.log 2>&1 &？

还是CUDA_VISIBLE_DEVICES=0 nohup python -u train.py  --weight_path weight/mobilenetv3.pth --gpu_id 0 > nohup.log 2>&1 &？
which one？thx

**Comment by argusswift** [comment]
> CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --weight_path weight/mobilenetv3.pth --gpu_id 0 > nohup.log 2>&1 &

CUDA_VISIBLE_DEVICES=0 nohup python -u train.py --weight_path weight/mobilenetv3.pth --gpu_id 0 > nohup.log 2>&1 &
