### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual $DATA_TEST --eval --mode det

### ISSUE THREAD

**Issue by c7934597** [argusswift/YOLOv4-pytorch#129]
我的狀況跟上一篇不太一樣，我是下載mobilenetv3預權重，然後訓練自定義模型
Customer_DATA = {
    "NUM": 1,  # your dataset number
    "CLASSES": ["phone"],  # your dataset class
}

訓練完後，我使用這個指令要偵測圖片會跳出以下錯誤，模型一直載不進去
loading weight file from : weight/best.pt
Traceback (most recent call last):
  File "eval_voc.py", line 157, in <module>
    mode=opt.mode
  File "eval_voc.py", line 38, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 47, in __load_model_weights
    self.__model.load_state_dict(chkpt["model"])
KeyError: 'model'

發現是在eval_voc.py這行一直卡住
self.__model.load_state_dict(chkpt["model"])

前面build出來的模型權重放不進去的樣子
self.__model = Build_Model(showatt=self.__showatt).to(self.__device)

我在指令前面增加sudo，它錯誤會變成
Traceback (most recent call last):
  File "eval_custom.py", line 1, in <module>
    import utils.gpu as gpu
  File "/home/minggatsby/GitHub/YOLOv4-pytorch/utils/__init__.py", line 1, in <module>
    from .datasets import Build_Dataset
  File "/home/minggatsby/GitHub/YOLOv4-pytorch/utils/datasets.py", line 7, in <module>
    import torch
  File "/home/minggatsby/.local/lib/python3.6/site-packages/torch/__init__.py", line 190, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

再追蹤問題下去發現是mmcv問題，我是用rtx3090 pytorch1.7.1+cuda11.0，還再研究要怎灌正確mmcv版本
Traceback (most recent call last):
  File "eval_voc.py", line 2, in <module>
    from model.build_model import Build_Model
  File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/build_model.py", line 8, in <module>
    from model.YOLOv4 import YOLOv4
  File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/YOLOv4.py", line 8, in <module>
    from .layers.global_context_block import ContextBlock2d
  File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/layers/global_context_block.py", line 3, in <module>
    from mmcv.cnn import constant_init, kaiming_init
ModuleNotFoundError: No module named 'mmcv'

**Comment by argusswift** [comment]
> 我的狀況跟上一篇不太一樣，我是下載mobilenetv3預權重，然後訓練自定義模型
> Customer_DATA = {
> "NUM": 1, # your dataset number
> "CLASSES": ["phone"], # your dataset class
> }
> 
> 訓練完後，我使用這個指令要偵測圖片會跳出以下錯誤，模型一直載不進去
> loading weight file from : weight/best.pt
> Traceback (most recent call last):
> File "eval_voc.py", line 157, in
> mode=opt.mode
> File "eval_voc.py", line 38, in **init**
> self.__load_model_weights(weight_path)
> File "eval_voc.py", line 47, in __load_model_weights
> self.__model.load_state_dict(chkpt["model"])
> KeyError: 'model'
> 
> 發現是在eval_voc.py這行一直卡住
> self.__model.load_state_dict(chkpt["model"])
> 
> 前面build出來的模型權重放不進去的樣子
> self.__model = Build_Model(showatt=self.__showatt).to(self.__device)
> 
> 我在指令前面增加sudo，它錯誤會變成
> Traceback (most recent call last):
> File "eval_custom.py", line 1, in
> import utils.gpu as gpu
> File "/home/minggatsby/GitHub/YOLOv4-pytorch/utils/**init**.py", line 1, in
> from .datasets import Build_Dataset
> File "/home/minggatsby/GitHub/YOLOv4-pytorch/utils/datasets.py", line 7, in
> import torch
> File "/home/minggatsby/.local/lib/python3.6/site-packages/torch/**init**.py", line 190, in
> from torch._C import *
> ImportError: numpy.core.multiarray failed to import
> 
> 再追蹤問題下去發現是mmcv問題，我是用rtx3090 pytorch1.7.1+cuda11.0，還再研究要怎灌正確mmcv版本
> Traceback (most recent call last):
> File "eval_voc.py", line 2, in
> from model.build_model import Build_Model
> File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/build_model.py", line 8, in
> from model.YOLOv4 import YOLOv4
> File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/YOLOv4.py", line 8, in
> from .layers.global_context_block import ContextBlock2d
> File "/home/minggatsby/GitHub/YOLOv4-pytorch/model/layers/global_context_block.py", line 3, in
> from mmcv.cnn import constant_init, kaiming_init
> ModuleNotFoundError: No module named 'mmcv'

MMCV is a foundational python library for global_context_block.You can make a reference Installation:
https://github.com/open-mmlab/mmcv

**Comment by c7934597** [comment]
我安裝好mmcv了 然後又恢復到model載不進去的狀況，然後我參數改成載last.pt就可以，載best.pt就會載不進去，
想請問為什麼best.pt的模型大小是其他模型和last.pt的一半呢？

**Comment by jingtianyilong** [comment]
`best.pt` has a different structure 
https://github.com/argusswift/YOLOv4-pytorch/blob/c508af33ab4a5abb588f67c1e04237abc17af4e2/train.py#L107-L125
Basically, you can use 
```
chkpt = torch.load('best.pt', map_location=self.device)
self.yolov4.load_state_dict(chkpt)
```

**Comment by c7934597** [comment]
Thank you so much, it has been solved. I am trying to convert to tensorRT for Xavier Nx.
