### ISSUE TITLE
VOC训练的mobilenetv3-yolov4 在evaluate时出错

### ISSUE THREAD

**Issue by qrzeffort** [argusswift/YOLOv4-pytorch#131]
当我按照
CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual data --eval --mode val
测试时，出现报错：
Traceback (most recent call last):
  File "eval_voc.py", line 142, in <module>
    Evaluation(
  File "eval_voc.py", line 38, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 47, in __load_model_weights
    self.__model.load_state_dict(chkpt["model"])
KeyError: 'model'
我测试图片的放置顺序是：
data
------test
在test文件夹中放置了5000张图片

**Comment by jingtianyilong** [comment]
`chkpt' have no key called `model`
try with `load_state_dict(chkpt)`
Notice that the `best.pt` and `last.pt` have drastically different structure.

**Comment by qrzeffort** [comment]
> `chkpt` have no key called `model`
> try with `load_state_dict(chkpt)`
> Notice that the `best.pt` and `last.pt` have drastically differe

**Comment by qrzeffort** [comment]
I tried load_state_dict(chkpt),and report:
RuntimeError: Error(s) in loading state_dict for Build_Model:
	Missing key(s) in state_dict: "_Build_Model__yolov4.attention.conv_mask.weight", "_Build_Model__yolov4.attention.conv_mask.bias", "_Build_Model__yolov4.attention.channel_add_conv.0.weight", "_Build_Model__yolov4.attention.channel_add_conv.0.bias", "_Build_Model__yolov4.attention.channel_add_conv.1.weight", "_Build_Model__yolov4.attention.channel_add_conv.1.bias", "_Build_Model__yolov4.attention.channel_add_conv.3.weight", "_Build_Model__yolov4.attention.channel_add_conv.3.bias".

**Comment by fangdaoyou** [comment]
> 我尝试了load_state_dict（chkpt），并报告：
> RuntimeError：加载Build_Model的state_dict时出错：state_dict中的
> 键缺失：“ _Build_Model__yolov4.attention.conv_mask.weight”，“ _Build_Model__yolov4.attention.conv_mask.bias”， “ _Build_Model__yolov4.attention.channel_add_conv.0.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.0.bias”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.bias” .attention.channel_add_conv.3.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.3.bias”。

您好！我遇到了相同的问题，将参数换成‘det’能够跑出结果，但是‘val’不行。请问您解决了吗，如果解决了能教授一下吗，非常感谢。

**Comment by cymdhx** [comment]
> `chkpt`没有呼叫键`model`
> 试着`load_state_dict(chkpt)`
> 注意，`best.pt`和`last.pt`有着截然不同的结构。

![image](https://user-images.githubusercontent.com/73769530/104928372-86d9d780-59dd-11eb-8c8f-74c340b5d66f.png)
我想问问这是为什么

**Comment by cymdhx** [comment]
> > 我尝试了load_state_dict（chkpt），并报告： RuntimeError：加载Build_Model的state_dict时出错：state_dict中的 键缺失：“ _Build_Model__yolov4.attention.conv_mask.weight”，“ _Build_Model__yolov4.attention.conv_mask.bias”， “ _Build_Model__yolov4.attention.channel_add_conv.0.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.0.bias”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.bias” .attention.channel_add_conv.3.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.3.bias”。
> 
> 您好！我遇到了相同的问题，将参数换成‘det’能够跑出结果，但是‘val’不行。请问您解决了吗，如果解决了能教授一下吗，非常感谢。

老哥 你知道KeyError: 'model'怎么解决的吗 麻烦教一下

**Comment by fangdaoyou** [comment]
> > > 我尝试了load_state_dict（chkpt），并报告： RuntimeError：加载Build_Model的state_dict时出错：state_dict中的 键缺失：“ _Build_Model__yolov4.attention.conv_mask.weight”，“ _Build_Model__yolov4.attention.conv_mask.bias”， “ _Build_Model__yolov4.attention.channel_add_conv.0.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.0.bias”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.1.bias” .attention.channel_add_conv.3.weight”，“ _ Build_Model__yolov4.attention.channel_add_conv.3.bias”。
> > 
> > 
> > 您好！我遇到了相同的问题，将参数换成‘det’能够跑出结果，但是‘val’不行。请问您解决了吗，如果解决了能教授一下吗，非常感谢。
> 
> 老哥 你知道KeyError: 'model'怎么解决的吗 麻烦教一下

直接改成load_state_dict(chkpt)
