### ISSUE TITLE
modesize.py分析出错

### ISSUE THREAD

**Issue by indigohana** [argusswift/YOLOv4-pytorch#132]
error:
Traceback (most recent call last):
  File "modelsize.py", line 62, in <module>
    modelsize(net, in_img)
  File "modelsize.py", line 32, in modelsize
    out_sizes.append(np.array(out[j].size()))
AttributeError: 'list' object has no attribute 'size'

我这里自己修改了一下：
将原line32改成：
                `out_sizes_j = np.array(out[j])`
                `out_sizes.append(out_sizes_j.shape)`

请问有人遇到过同样的问题吗？可以交流一下，谢谢！

**Comment by argusswift** [comment]
> error:
> Traceback (most recent call last):
> File "modelsize.py", line 62, in
> modelsize(net, in_img)
> File "modelsize.py", line 32, in modelsize
> out_sizes.append(np.array(out[j].size()))
> AttributeError: 'list' object has no attribute 'size'
> 
> 我这里自己修改了一下：
> 将原line32改成：
> `out_sizes_j = np.array(out[j])`
> `out_sizes.append(out_sizes_j.shape)`
> 
> 请问有人遇到过同样的问题吗？可以交流一下，谢谢！

bug已修复，感谢指正

**Comment by indigohana** [comment]
> > error:
> > Traceback (most recent call last):
> > File "modelsize.py", line 62, in
> > modelsize(net, in_img)
> > File "modelsize.py", line 32, in modelsize
> > out_sizes.append(np.array(out[j].size()))
> > AttributeError: 'list' object has no attribute 'size'
> > 我这里自己修改了一下：
> > 将原line32改成：
> > `out_sizes_j = np.array(out[j])`
> > `out_sizes.append(out_sizes_j.shape)`
> > 请问有人遇到过同样的问题吗？可以交流一下，谢谢！
> 
> bug已修复，感谢指正

你好，我遇到了越界问题，提示如下（看issue里很多人提到：

> label[best_detect][yind, xind, best_anchor, 0:4] = bbox_xywh
> IndexError: index 52 is out of bounds for axis 1 with size 52

然后我在datasets.py进行了改动，对xind/yind的上下限进行了判断：
`if int(xind) > int(train_output_size[i]-1): 
    xind = (train_output_size[i]-1).astype(np.int32) 
if int(xind) < 0: 
    xind = 0 
if int(yind) > int(train_output_size[i]-1): 
    xind = (train_output_size[i]-1).astype(np.int32) 
if int(yind) < 0: 
    yind = 0`
但是训练出来效果很差，请问作者有没有解决的建议呢？感谢！

**Comment by argusswift** [comment]
> > > error:
> > > Traceback (most recent call last):
> > > File "modelsize.py", line 62, in
> > > modelsize(net, in_img)
> > > File "modelsize.py", line 32, in modelsize
> > > out_sizes.append(np.array(out[j].size()))
> > > AttributeError: 'list' object has no attribute 'size'
> > > 我这里自己修改了一下：
> > > 将原line32改成：
> > > `out_sizes_j = np.array(out[j])`
> > > `out_sizes.append(out_sizes_j.shape)`
> > > 请问有人遇到过同样的问题吗？可以交流一下，谢谢！
> > 
> > 
> > bug已修复，感谢指正
> 
> 你好，我遇到了越界问题，提示如下（看issue里很多人提到：
> 
> > label[best_detect][yind, xind, best_anchor, 0:4] = bbox_xywh
> > IndexError: index 52 is out of bounds for axis 1 with size 52
> 
> 然后我在datasets.py进行了改动，对xind/yind的上下限进行了判断：
> 
> > if int(xind) > int(train_output_size[i]-1):
> > xind = (train_output_size[i]-1).astype(np.int32)
> > if int(xind) < 0:
> > xind = 0
> > if int(yind) > int(train_output_size[i]-1):
> > xind = (train_output_size[i]-1).astype(np.int32)
> > if int(yind) < 0:
> > yind = 0`
> 
> 但是训练出来效果很差，请问作者有没有解决的建议呢？感谢！

数组越界判断会稍微影响评估精度，但不至于导致很差的结果。你应该检查其他部分是否有错误。

**Comment by indigohana** [comment]
好的，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tomas Yang"<notifications@github.com&gt;; 
发送时间: 2021年1月22日(星期五) 中午12:06
收件人: "argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;; 
抄送: "1240653567"<1240653567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [argusswift/YOLOv4-pytorch] modesize.py分析出错 (#132)





    
error:
 Traceback (most recent call last):
 File "modelsize.py", line 62, in
 modelsize(net, in_img)
 File "modelsize.py", line 32, in modelsize
 out_sizes.append(np.array(out[j].size()))
 AttributeError: 'list' object has no attribute 'size'
 我这里自己修改了一下：
 将原line32改成：
 out_sizes_j = np.array(out[j])
 out_sizes.append(out_sizes_j.shape)
 请问有人遇到过同样的问题吗？可以交流一下，谢谢！
  
bug已修复，感谢指正
  
你好，我遇到了越界问题，提示如下（看issue里很多人提到：
  
label[best_detect][yind, xind, best_anchor, 0:4] = bbox_xywh
 IndexError: index 52 is out of bounds for axis 1 with size 52
  
然后我在datasets.py进行了改动，对xind/yind的上下限进行了判断：
  
if int(xind) &gt; int(train_output_size[i]-1):
 xind = (train_output_size[i]-1).astype(np.int32)
 if int(xind) < 0:
 xind = 0
 if int(yind) &gt; int(train_output_size[i]-1):
 xind = (train_output_size[i]-1).astype(np.int32)
 if int(yind) < 0:
 yind = 0`
  
但是训练出来效果很差，请问作者有没有解决的建议呢？感谢！
  
数组越界判断会稍微影响评估精度，但不至于导致很差的结果。你应该检查其他部分是否有错误。

**Comment by argusswift** [comment]
> 好的，谢谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tomas Yang"<notifications@github.com&gt;; 发送时间: 2021年1月22日(星期五) 中午12:06 收件人: "argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;; 抄送: "1240653567"<1240653567@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [argusswift/YOLOv4-pytorch] modesize.py分析出错 (#132) error: Traceback (most recent call last): File "modelsize.py", line 62, in modelsize(net, in_img) File "modelsize.py", line 32, in modelsize out_sizes.append(np.array(out[j].size())) AttributeError: 'list' object has no attribute 'size' 我这里自己修改了一下： 将原line32改成： out_sizes_j = np.array(out[j]) out_sizes.append(out_sizes_j.shape) 请问有人遇到过同样的问题吗？可以交流一下，谢谢！ bug已修复，感谢指正 你好，我遇到了越界问题，提示如下（看issue里很多人提到： label[best_detect][yind, xind, best_anchor, 0:4] = bbox_xywh IndexError: index 52 is out of bounds for axis 1 with size 52 然后我在datasets.py进行了改动，对xind/yind的上下限进行了判断： if int(xind) &gt; int(train_output_size[i]-1): xind = (train_output_size[i]-1).astype(np.int32) if int(xind) < 0: xind = 0 if int(yind) &gt; int(train_output_size[i]-1): xind = (train_output_size[i]-1).astype(np.int32) if int(yind) < 0: yind = 0` 但是训练出来效果很差，请问作者有没有解决的建议呢？感谢！ 数组越界判断会稍微影响评估精度，但不至于导致很差的结果。你应该检查其他部分是否有错误。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不客气

**Comment by shuang1204** [comment]
运行modersize.py文件时出现Traceback (most recent call last):
  File "modelsize.py", line 54, in <module>
    from model.build_model import Build_Model
ModuleNotFoundError: No module named 'model'问题，请问该怎么解决@Tomas Yang argusswift
