### ISSUE TITLE
How should I evaluate the mobilenetv2-yolov4 model

### ISSUE THREAD

**Issue by qrzeffort** [argusswift/YOLOv4-pytorch#139]
I want to use the given mobilenetv2-YOLOv4 weights to evaluate on the VOC07+12 data set, but according to the guidelines, I cannot run normally. Are there any specific steps? The problem I encountered is described in #131, thank you very much!

**Comment by jingtianyilong** [comment]
Seems like you are loading a mobilenet_yolov4 weight but the current model you have is a CSPDarkenet yolov4.

**Comment by qrzeffort** [comment]
> Seems like you are loading a mobilenet_yolov4 weight but the current model you have is a CSPDarkenet yolov4.
How can I change my model structure，

**Comment by jingtianyilong** [comment]
https://github.com/argusswift/YOLOv4-pytorch/blob/e370aabbb5a4a1aee3cb9090191471bb2ec7b673/config/yolov4_config.py#L9-L11
Check here.

**Comment by qrzeffort** [comment]
> https://github.com/argusswift/YOLOv4-pytorch/blob/e370aabbb5a4a1aee3cb9090191471bb2ec7b673/config/yolov4_config.py#L9-L11
> 
> 
> Check here.

I tried but still the problem：

Traceback (most recent call last):
  File "eval_voc.py", line 140, in <module>
    Evaluation(
  File "eval_voc.py", line 36, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 45, in __load_model_weights
    self.__model.load_state_dict(chkpt["model"])
KeyError: 'model'

**Comment by qrzeffort** [comment]
I don’t know how to solve it. I also tried the method in the previous issue.

**Comment by qrzeffort** [comment]
yolov4_config lines 4 to11
PROJECT_PATH = osp.abspath(osp.join(osp.dirname(__file__), '..'))
DATA_PATH = r"YOLOv4-pytorch-master\data"
MODEL_TYPE = {
    "TYPE": "Mobilenet-YOLOv4"
}  # YOLO type:YOLOv4, Mobilenet-YOLOv4 or Mobilenetv3-YOLOv4

**Comment by jingtianyilong** [comment]
> > https://github.com/argusswift/YOLOv4-pytorch/blob/e370aabbb5a4a1aee3cb9090191471bb2ec7b673/config/yolov4_config.py#L9-L11
> > 
> > Check here.
> 
> I tried but still the problem：
> 
> Traceback (most recent call last):
> File "eval_voc.py", line 140, in
> Evaluation(
> File "eval_voc.py", line 36, in **init**
> self.__load_model_weights(weight_path)
> File "eval_voc.py", line 45, in __load_model_weights
> self.__model.load_state_dict(chkpt["model"])
> KeyError: 'model'

The compiler tells you that the `chkpt` don't have a key called `model`. So check the structure of the chkpt, and modify the code respectively. In this case I would blind guess that you can do `load_state_dict(chkpt)`

**Comment by qrzeffort** [comment]
The above problem is solved, thank you very much, but another error is reported next, is there something wrong with my $DATA_TEST?
  File "\YOLOv4-pytorch-master\eval\evaluator.py", line 71, in Single_APs_voc
    bboxes_prd = self.get_bbox(img, self.multi_scale_test, self.flip_test)
  File "\YOLOv4-pytorch-master\eval\evaluator.py", line 103, in get_bbox
    self.__predict(img, test_input_size, valid_scale, mode)
  File "\YOLOv4-pytorch-master\eval\evaluator.py", line 123, in __predict
    org_h, org_w, _ = org_img.shape
ValueError: not enough values to unpack (expected 3, got 0)

The command I run is：
python eval_voc.py --weight_path weight/voc_best.pt --gpu_id 0 --visiual data --eval --mode val

The path of my dataset is：
data
    --------VOCdevkit
    --------VOC2007

**Comment by qrzeffort** [comment]
I tried issue #127 but still the same report

**Comment by jingtianyilong** [comment]
`(expected 3, got 0)`
0 not 2
This is your problem. Yours and the #127  is totally different.
Your problem is that your `org_img` is empty. Trace back to your file and see why this is empty.

**Comment by jingtianyilong** [comment]
And please try to debug by yourself first. And search on internet before asking questions. You can solve 99% of the problem by yourself, just by searching online. Notice that others are doing well with the same code, the problem normally will be on your side. Find out some way to debug with the help of the error information. They are really intuitive on python. 

The issue section is designed for reporting problem with bugs and suggestion for improvements. Not a general questioning platform.
