### ISSUE TITLE
 assert img is not None, 'File Not Found ' + img_path

### ISSUE THREAD

**Issue by gaasing** [argusswift/YOLOv4-pytorch#14]
训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错

`assert img is not None, 'File Not Found ' + img_path`
AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg

图片已放置在data/JPEGImages文件夹内

请问问题出在哪里？

https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69

**Comment by whyisma** [comment]
> 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> 
> `assert img is not None, 'File Not Found ' + img_path`
> AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> 
> 图片已放置在data/JPEGImages文件夹内
> 
> 请问问题出在哪里？
> 
> https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69

可以自己debug一下，看annotations列表是否为空。

**Comment by gaasing** [comment]
> > 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> > `assert img is not None, 'File Not Found ' + img_path`
> > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> > 图片已放置在data/JPEGImages文件夹内
> > 请问问题出在哪里？
> > https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69
> 
> 可以自己debug一下，看annotations列表是否为空。

在data文件夹里，Annotations和JPEGImages文件夹分别放好了标签和图片文件。
请问成功训练起来了吗，可否指导一下。

**Comment by whyisma** [comment]
> > > 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> > > `assert img is not None, 'File Not Found ' + img_path`
> > > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> > > 图片已放置在data/JPEGImages文件夹内
> > > 请问问题出在哪里？
> > > https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69
> > 
> > 
> > 可以自己debug一下，看annotations列表是否为空。
> 
> 在data文件夹里，Annotations和JPEGImages文件夹分别放好了标签和图片文件。
> 请问成功训练起来了吗，可否指导一下。

我跑通了整个项目的，data文件里放置一个txt文档，类似于这个`E:\YOLOv4-pytorch\VOCdevkit\VOC2007\JPEGImages\000000000139.jpg 358,218,414,320,0 `，上面有训练图片的地址和对应的标注框

**Comment by gaasing** [comment]
> > > > 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> > > > `assert img is not None, 'File Not Found ' + img_path`
> > > > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> > > > 图片已放置在data/JPEGImages文件夹内
> > > > 请问问题出在哪里？
> > > > https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69
> > > 
> > > 
> > > 可以自己debug一下，看annotations列表是否为空。
> > 
> > 
> > 在data文件夹里，Annotations和JPEGImages文件夹分别放好了标签和图片文件。
> > 请问成功训练起来了吗，可否指导一下。
> 
> 我跑通了整个项目的，data文件里放置一个txt文档，类似于这个`E:\YOLOv4-pytorch\VOCdevkit\VOC2007\JPEGImages\000000000139.jpg 358,218,414,320,0 `，上面有训练图片的地址和对应的标注框

我的test_annotation和train_annotation的TXT文档是这样的。
/home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/0000f77c-6257be58.jpg 1125,133,1156,210,9 1156,136,1191,210,9 1101,211,1170,233,8 0,0,100,122,8 45,254,357,487,0 507,221,908,442,0 0,0,102,133,8
类似这样的格式，是使用作者提供的工具生成的，请问这样写路径（绝对路径）有没有问题
在linux系统上跑的

我的数据集目录结构是这样的
-YOLOv4-pytorch
---data
-----Annotations
-------943f0721-97e0dfd4.xml
-------...（存放标签的文件夹）
-----JPEGImages
-------943f0721-97e0dfd4.jpg
-------...（存放图片的文件夹）

错误代码：
AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg

**Comment by whyisma** [comment]
> > > > > 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> > > > > `assert img is not None, 'File Not Found ' + img_path`
> > > > > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> > > > > 图片已放置在data/JPEGImages文件夹内
> > > > > 请问问题出在哪里？
> > > > > https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69
> > > > 
> > > > 
> > > > 可以自己debug一下，看annotations列表是否为空。
> > > 
> > > 
> > > 在data文件夹里，Annotations和JPEGImages文件夹分别放好了标签和图片文件。
> > > 请问成功训练起来了吗，可否指导一下。
> > 
> > 
> > 我跑通了整个项目的，data文件里放置一个txt文档，类似于这个`E:\YOLOv4-pytorch\VOCdevkit\VOC2007\JPEGImages\000000000139.jpg 358,218,414,320,0 `，上面有训练图片的地址和对应的标注框
> 
> 我的test_annotation和train_annotation的TXT文档是这样的。
> /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/0000f77c-6257be58.jpg 1125,133,1156,210,9 1156,136,1191,210,9 1101,211,1170,233,8 0,0,100,122,8 45,254,357,487,0 507,221,908,442,0 0,0,102,133,8
> 类似这样的格式，是使用作者提供的工具生成的，请问这样写路径（绝对路径）有没有问题
> 在linux系统上跑的
> 
> 我的数据集目录结构是这样的
> -YOLOv4-pytorch
> ---data
> -----Annotations
> -------943f0721-97e0dfd4.xml
> -------...（存放标签的文件夹）
> -----JPEGImages
> -------943f0721-97e0dfd4.jpg
> -------...（存放图片的文件夹）
> 
> 错误代码：
> AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg

你这个文件的命名方式有点奇怪，你试试改一下图片名和标注名呢

**Comment by gaasing** [comment]
> > > > > > 训练自己的数据集（BDD100K），按照要求已转为VOC格式的XML文件，并通过xml_to_txt.py成功生成TXT文件，然后在cfg文件修改好DATA_PATH（使用绝对路径），运行train.py报错
> > > > > > `assert img is not None, 'File Not Found ' + img_path`
> > > > > > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> > > > > > 图片已放置在data/JPEGImages文件夹内
> > > > > > 请问问题出在哪里？
> > > > > > https://github.com/argusswift/YOLOv4-pytorch/blob/bcb1698169d3ecbf8bdd726adf140897404c4acc/utils/datasets.py#L69
> > > > > 
> > > > > 
> > > > > 可以自己debug一下，看annotations列表是否为空。
> > > > 
> > > > 
> > > > 在data文件夹里，Annotations和JPEGImages文件夹分别放好了标签和图片文件。
> > > > 请问成功训练起来了吗，可否指导一下。
> > > 
> > > 
> > > 我跑通了整个项目的，data文件里放置一个txt文档，类似于这个`E:\YOLOv4-pytorch\VOCdevkit\VOC2007\JPEGImages\000000000139.jpg 358,218,414,320,0 `，上面有训练图片的地址和对应的标注框
> > 
> > 
> > 我的test_annotation和train_annotation的TXT文档是这样的。
> > /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/0000f77c-6257be58.jpg 1125,133,1156,210,9 1156,136,1191,210,9 1101,211,1170,233,8 0,0,100,122,8 45,254,357,487,0 507,221,908,442,0 0,0,102,133,8
> > 类似这样的格式，是使用作者提供的工具生成的，请问这样写路径（绝对路径）有没有问题
> > 在linux系统上跑的
> > 我的数据集目录结构是这样的
> > -YOLOv4-pytorch
> > ---data
> > -----Annotations
> > -------943f0721-97e0dfd4.xml
> > -------...（存放标签的文件夹）
> > -----JPEGImages
> > -------943f0721-97e0dfd4.jpg
> > -------...（存放图片的文件夹）
> > 错误代码：
> > AssertionError: File Not Found /home/amax/lf2/YOLOv4-pytorch/data/JPEGImages/943f0721-97e0dfd4.jpg
> 
> 你这个文件的命名方式有点奇怪，你试试改一下图片名和标注名呢

谢谢你，我终于找到自己的问题所在，我的JPEGImages文件夹名大小写字母搞错了。麻烦了。
