### ISSUE TITLE
Convert Onnx to TensorRT

### ISSUE THREAD

**Issue by c7934597** [argusswift/YOLOv4-pytorch#141]
請問Mobilenetv3-YOLOv4的模型有辦法轉成onnx and tensorRT嗎？

官方yolov4 可以使用 https://github.com/jkjung-avt
那這版要怎麼轉呢，目前有需求部屬在邊緣裝置，謝謝。

**Comment by jingtianyilong** [comment]
Great point. Also looking forward. In general torch model should be able to convert to TRT using onnx. I haven't get my hands on this. Would be really interesting to see some instructions or experience sharing

**Comment by argusswift** [comment]
The onnx_transform.py has just been uploaded.
