### ISSUE TITLE
测试的时候出现Available platform plugins are: xcb.问题

### ISSUE THREAD

**Issue by shuang1204** [argusswift/YOLOv4-pytorch#146]
qt.qpa.xcb: could not connect to display localhost:33.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/media/sda1/renhonge/anaconda3/envs/pytorch/lib/python3.7/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
@argusswift 请问这个问题该如何解决呀

**Comment by jingtianyilong** [comment]
Check your `cv2` reinstall it.

**Comment by shuang1204** [comment]
我用cuda11,python 3.7，opencv-python 4.4.0.46训练的数据集，请问该重装cv2的哪个版本？，以下是我环境中装的所有包
Package             Version
------------------- -------------------
addict              2.4.0
anykeystore         0.2
apex                0.1
certifi             2020.12.5
chardet             4.0.0
click               7.1.2
cryptacular         1.5.5
cycler              0.10.0
Cython              0.29.21
defusedxml          0.6.0
hupper              1.10.2
idna                2.10
kiwisolver          1.3.1
MarkupSafe          1.1.1
matplotlib          3.3.3
mmcv                1.2.5
numpy               1.19.4
oauthlib            3.1.0
opencv-python       4.4.0.46
PasteDeploy         2.1.1
pbkdf2              1.3
pickleshare         0.7.5
Pillow              8.0.1
pip                 20.3.3
plaster             1.0
plaster-pastedeploy 0.7
protobuf            3.14.0
pycocotools         2.0.2
pyparsing           2.4.7
PyQt5               5.15.2
pyqt5-plugins       5.15.2.2.0.1
PyQt5-sip           12.8.1
pyqt5-tools         5.15.2.3.0.2
pyramid             1.10.5
pyramid-mailer      0.15.1
python-dateutil     2.8.1
python-dotenv       0.15.0
python3-openid      3.2.0
PyYAML              5.3.1
qt5-applications    5.15.2.2.1
qt5-tools           5.15.2.1.0.1
repoze.sendmail     4.4.1
requests            2.25.1
requests-oauthlib   1.3.0
setuptools          51.0.0.post20201207
six                 1.15.0
SQLAlchemy          1.3.22
tensorboardX        2.1
torch               1.7.1
torchvision         0.8.2
tqdm                4.55.0
transaction         3.0.1
translationstring   1.4
typing-extensions   3.7.4.3
urllib3             1.26.2
velruse             1.1.1
venusian            3.0.0
WebOb               1.8.6
wheel               0.36.2
WTForms             2.3.3
wtforms-recaptcha   0.3.2
yapf                0.30.0
zope.deprecation    4.4.0
zope.interface      5.2.0
zope.sqlalchemy     1.3
@argusswift @jingtianyilong

**Comment by jingtianyilong** [comment]
I thought it only matters whether you reinstall or not. Not the version. Try to set up a new env with conda. I find it simple and trust worthy

**Comment by shuang1204** [comment]
重新建立新的虚拟环境，还是会出现同样的问题，请问是怎么回事呀@argusswift @jingtianyilong

**Comment by shuang1204** [comment]
安装了opencv-contrib-python-headless包以后，又出现了新的问题
[2021-02-18 10:51:15,246]-[eval_voc.py line:80]:val images : data/det-result.jpg 
Traceback (most recent call last):
  File "eval_voc.py", line 161, in <module>
    mode=opt.mode
  File "eval_voc.py", line 85, in detection
    bboxes_prd = self.__evalter.get_bbox(img, v, mode=self.__mode)
  File "/media/sda1/renhonge/rszhang/attentionyolov4/atYOLO/attention/YOLOv4-pytorch-master/eval/evaluator.py", line 98, in get_bbox
    self.__predict(img, test_input_size, valid_scale, mode)
  File "/media/sda1/renhonge/rszhang/attentionyolov4/atYOLO/attention/YOLOv4-pytorch-master/eval/evaluator.py", line 134, in __predict
    self.__show_heatmap(atten, org_img)
  File "/media/sda1/renhonge/rszhang/attentionyolov4/atYOLO/attention/YOLOv4-pytorch-master/eval/evaluator.py", line 138, in __show_heatmap
    imshowAtt(beta, img)
  File "/media/sda1/renhonge/rszhang/attentionyolov4/atYOLO/attention/YOLOv4-pytorch-master/utils/heatmap.py", line 53, in imshowAtt
    cv2.imshow("img", cam)
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-n24k10t1/opencv/modules/highgui/src/window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'
请问该怎么解决呀@argusswift @jingtianyilong

**Comment by shuang1204** [comment]
更改了opencv-pytorch的版本后，上述问题得到了解决，出现了新的问题
Traceback (most recent call last):
  File "eval_voc.py", line 161, in <module>
    mode=opt.mode
  File "eval_voc.py", line 83, in detection
    assert img is not None
AssertionError
请问该怎么解决呀@argusswift @jingtianyilong

**Comment by jingtianyilong** [comment]
obviously, the image is none. Check your image_path

**Comment by shuang1204** [comment]
@jingtianyilong谢谢
问题已解决
