### ISSUE TITLE
get_map.py里的detection-results中的txt文件该如何生成？

### ISSUE THREAD

**Issue by minuet-red** [argusswift/YOLOv4-pytorch#151]
![image](https://user-images.githubusercontent.com/78399534/107512838-5b17cf00-6be2-11eb-8e5d-f0bc38514e86.png)
请问get_map.py里的detection-results中的txt文件该如何生成？
求解答

**Comment by jingtianyilong** [comment]
get_map is only for separate use.
check https://github.com/Cartucho/mAP for more reference.
