### ISSUE TITLE
mobilenet weights download

### ISSUE THREAD

**Issue by mikael10j** [argusswift/YOLOv4-pytorch#153]
Hi, I'm from France and it seems that I can't create a baidu account. Is there any other way to download the weights of the mobilenet versions of your YOLOV4 ?
Thanks !

**Comment by 108368062** [comment]
Maybe you can try this method and create an account in the "Xiaodu Speaker" application at https://app.mi.com/details?id=com.xiaodu.smartspeaker

**Comment by mikael10j** [comment]
Hi, thank you for your answer. I eventually switched to scaled-yolo that has a pytorch implementation from the authors of the paper. In addition, they provide the weights through a google drive that doesn't require to register.
