### ISSUE TITLE
is:issue is:open Darknet pre-trained weight : yolov4这个链接打不开

### ISSUE THREAD

**Issue by mynameisliuliu** [argusswift/YOLOv4-pytorch#16]
is:issue is:open Darknet pre-trained weight : yolov4这个链接打不开！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by kunyaoli** [comment]
我下好了 ，你QQ多少 我分享给你

**Comment by kunyaoli** [comment]
> is:issue is:open Darknet pre-trained weight : yolov4这个链接打不开！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

我下好了 ，你QQ多少 我分享给你

**Comment by huanal** [comment]
> > is:issue is:open Darknet pre-trained weight : yolov4这个链接打不开！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> 
> 我下好了 ，你QQ多少 我分享给你

可以发给我吗，1076857163，谢谢

**Comment by brightdingpei** [comment]
是否也可以发给我，3198641042，非常感谢谢谢

**Comment by huanal** [comment]
你好，我也还没拿到，拿到了给你发




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argusswift/YOLOv4-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 下午4:24
收件人:&nbsp;"argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"娄丽娜"<1076857163@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [argusswift/YOLOv4-pytorch] is:issue is:open Darknet pre-trained weight : yolov4这个链接打不开 (#16)





 
是否也可以发给我，3198641042，非常感谢谢谢
