### ISSUE TITLE
model link分享百度网盘密码

### ISSUE THREAD

**Issue by Zpadger** [argusswift/YOLOv4-pytorch#175]
哪位好心人告诉一下mobilenetv2-YOLOV4的model link百度网盘密码，没找到......

**Comment by Zpadger** [comment]
找到了...

**Comment by zhangbo2008** [comment]
多少啊哥们???????????
我没找到

**Comment by zhangbo2008** [comment]
原来就是边上写的code:args 啊..............

**Comment by abhigoku10** [comment]
@Zpadger  can you please share it on google drive and share the link here thanks in adavance
