### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Anleeno-Xu** [argusswift/YOLOv4-pytorch#177]
1.Voc数据集一定要分三个目录吗，能不能合成一个，合成之后载入的地方怎么改
2.自己的数据集是不是也要按照这三个目录分，然后每一个里面都是相同的vocdevket/voc2007/这样的

**Comment by Anleeno-Xu** [comment]
使用默认的设置验证voc数据集4952张测试集图片结果花了半个多小时是什么情况？
CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/voc_best.pt --gpu_id 0 --visiual dataset --mode val

**Comment by cqray1990** [comment]
@Anleeno-Xu你验证后ｍＡＰ多少？
