### ISSUE TITLE
detect error

### ISSUE THREAD

**Issue by kunyaoli** [argusswift/YOLOv4-pytorch#18]
您好，我使用了您训练的好的VOC模型进行测试，下载好您的代码之后，配置文件修改成了Mobilenet-YOLOv4，但是加载模型的时候报错了Initing PredictNet weights----->RuntimeError: Error(s) in loading state_dict for Build_Model:
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.0.1.weight: copying a param with shape torch.Size([75, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 32, 1, 1]).
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.0.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.1.1.weight: copying a param with shape torch.Size([75, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 96, 1, 1]).
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.1.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([18]).
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.2.1.weight: copying a param with shape torch.Size([75, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([18, 1280, 1, 1]).
	size mismatch for _Build_Model__yolov4.predict_net.predict_conv.2.1.bias: copying a param with shape torch.Size([75]) from checkpoint, the shape in current model is torch.Size([18]).

**Comment by xiaoweiChen** [comment]
老兄，和你遇到了相同的问题，我这边自己Debug了一下把这个问题解决了。

我用的代码是master分支的，bcb1698169d3ecbf8bdd726adf140897404c4acc

这个问题的原因：
`Build_Model`类中的`__nC`初始值为1(VOC的话应该是20，COCO的话应该是80)，因为代码当前的DATA_TYPE设置为Customer，具体在 config/yolov4_config.py的15行：
```python
...
# train
TRAIN = {
         "DATA_TYPE": 'Customer',  #DATA_TYPE: VOC ,COCO or Customer
         "TRAIN_IMG_SIZE": 416,
         "AUGMENT": True,
...
```
将`"DATA_TYPE": 'Customer'`改成`"DATA_TYPE": 'VOC'`，在运行就好了

Log有些多，就不全贴出来了，最后几行：
```
loading weight file from : weight\voc_best.pt
loading weight file is done
[2020-10-06 22:54:49,377]-[eval_voc.py line:70]:***********Start Detection****************
[2020-10-06 22:54:49,384]-[eval_voc.py line:73]:val images : images\COCO_val2014_1.jpg
[2020-10-06 22:54:50,929]-[eval_voc.py line:89]:saved images : .\detection_result/COCO_val2014_1.jpg
```

PS. 根据eval_voc.py:85行，
`path = os.path.join(cfg.PROJECT_PATH, "detection_result/{}".format(v))`
输出文件是在PROJECT_PATH下的detection_result文件夹。
由于使用的是opencv进行文件的写出，但opencv写出时目标父文件夹不存在的话，不会报错。
所以这里建议添加一个创建文件夹的语句，如下所示：
```
visualize_boxes(image=img, boxes=boxes, labels=class_inds, probs=scores, class_labels=self.__classes)
os.makedirs(os.path.join(cfg.PROJECT_PATH, "detection_result"), exist_ok=True) # 创建detection_result文件夹
path = os.path.join(cfg.PROJECT_PATH, "detection_result/{}".format(v))
```

**Comment by kunyaoli** [comment]
> 老兄，和你遇到了相同的问题，我这边自己Debug了一下把这个问题解决了。
> 
> 我用的代码是master分支的，bcb1698169d3ecbf8bdd726adf140897404c4acc
> 
> 这个问题的原因：
> `Build_Model`类中的`__nC`初始值为1(VOC的话应该是20，COCO的话应该是80)，因为代码当前的DATA_TYPE设置为Customer，具体在 config/yolov4_config.py的15行：
> 
> ```python
> ...
> # train
> TRAIN = {
>          "DATA_TYPE": 'Customer',  #DATA_TYPE: VOC ,COCO or Customer
>          "TRAIN_IMG_SIZE": 416,
>          "AUGMENT": True,
> ...
> ```
> 
> 将`"DATA_TYPE": 'Customer'`改成`"DATA_TYPE": 'VOC'`，在运行就好了
> 
> Log有些多，就不全贴出来了，最后几行：
> 
> ```
> loading weight file from : weight\voc_best.pt
> loading weight file is done
> [2020-10-06 22:54:49,377]-[eval_voc.py line:70]:***********Start Detection****************
> [2020-10-06 22:54:49,384]-[eval_voc.py line:73]:val images : images\COCO_val2014_1.jpg
> [2020-10-06 22:54:50,929]-[eval_voc.py line:89]:saved images : .\detection_result/COCO_val2014_1.jpg
> ```
> 
> PS. 根据eval_voc.py:85行，
> `path = os.path.join(cfg.PROJECT_PATH, "detection_result/{}".format(v))`
> 输出文件是在PROJECT_PATH下的detection_result文件夹。
> 由于使用的是opencv进行文件的写出，但opencv写出时目标父文件夹不存在的话，不会报错。
> 所以这里建议添加一个创建文件夹的语句，如下所示：
> 
> ```
> visualize_boxes(image=img, boxes=boxes, labels=class_inds, probs=scores, class_labels=self.__classes)
> os.makedirs(os.path.join(cfg.PROJECT_PATH, "detection_result"), exist_ok=True) # 创建detection_result文件夹
> path = os.path.join(cfg.PROJECT_PATH, "detection_result/{}".format(v))
> ```

谢谢，按照你的办法已经解决了，是默认这里的问题。
