### ISSUE TITLE
下载作者提供的voc_best.pt直接进行验证报错

### ISSUE THREAD

**Issue by Zpadger** [argusswift/YOLOv4-pytorch#181]
个人原因没时间训练了，想直接跑验证得到几张热力图，运行指令：`CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/voc_best.pt --gpu_id 0 --visiual dataset --mode val`
报错：

> ******************** Initing PredictNet weights ********************
initing Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
initing BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
initing Conv2d(256, 75, kernel_size=(1, 1), stride=(1, 1))
initing Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
initing BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
initing Conv2d(512, 75, kernel_size=(1, 1), stride=(1, 1))
initing Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
initing BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
initing Conv2d(1024, 75, kernel_size=(1, 1), stride=(1, 1))
loading weight file from : weight/voc_best.pt
Traceback (most recent call last):
  File "eval_voc.py", line 138, in <module>
    mode=opt.mode
  File "eval_voc.py", line 35, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 44, in __load_model_weights
    self.__model.load_state_dict(chkpt["model"])
KeyError: 'model'

翻看了之前的Issue感觉也没搞清楚解决方法，请问该如何解决呢？

**Comment by Zpadger** [comment]
问题已解决，能跑起来，就是挺卡的......服务器都连不上了......

**Comment by Yolanda2020** [comment]
请问作者提供的voc_best.pt您是从哪里下载的？

**Comment by Zpadger** [comment]
@Yolanda2020 在README里面：
![2021-05-21 10-55-43 的屏幕截图](https://user-images.githubusercontent.com/31385823/119075352-358d3380-ba23-11eb-8b0c-3f9fd561a490.png)

**Comment by Yolanda2020** [comment]
Thanks! Yukun Yang ***@***.*** Signature is customized by Netease Mail Master 在2021年05月21日 10:57，Zpadger 写道： @Yolanda2020 在README里面： — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Maokaicheng0725** [comment]
> 
> 
> 问题已解决，能跑起来，就是挺卡的......服务器都连不上了......

您好，我遇到了跟你一样 的问题！！！我debug了一晚上没找出原因，请问一下您是如何解决的呢？
