### ISSUE TITLE
Multicard training?

### ISSUE THREAD

**Issue by nightsnack** [argusswift/YOLOv4-pytorch#19]
Multicard training unsupported?

CUDA_VISIBLE_DEVICES=0,1,2,3 python -u train.py  --weight_path weight/yolov4.weights --gpu_id 0,1,2,3

usage: train.py [-h] [--weight_path WEIGHT_PATH] [--resume] [--gpu_id GPU_ID]
                [--log_path LOG_PATH] [--accumulate ACCUMULATE]
                [--fp_16 FP_16]
train.py: error: argument --gpu_id: invalid int value: '0,1,2,3'

**Comment by argusswift** [comment]
> Multicard training unsupported?
> 
> CUDA_VISIBLE_DEVICES=0,1,2,3 python -u train.py --weight_path weight/yolov4.weights --gpu_id 0,1,2,3
> 
> usage: train.py [-h] [--weight_path WEIGHT_PATH] [--resume] [--gpu_id GPU_ID]
> [--log_path LOG_PATH] [--accumulate ACCUMULATE]
> [--fp_16 FP_16]
> train.py: error: argument --gpu_id: invalid int value: '0,1,2,3'

Updating.....It will come soon
