### ISSUE TITLE
用自己的数据，运行train.py, 在Validate 时报错如下，是什么问题呢？

### ISSUE THREAD

**Issue by Yolanda2020** [argusswift/YOLOv4-pytorch#196]
YOLOv4-pytorch-master\eval\evaluator.py", line 123, in __predict
    org_h, org_w, _ = org_img.shape
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by jingtianyilong** [comment]
`org_img` is empty. Check your image path

**Comment by Yolanda2020** [comment]
Thanks, I have checked that the image path is correct, what else can lead to this problem? I am so confused.

**Comment by Yolanda2020** [comment]
Thanks, there are really some spelling mistakes in the image path.

**Comment by Yolanda2020** [comment]
> `org_img` is empty. Check your image path

Thanks, there is really a spelling mistake in the image path.

**Comment by xaioffff** [comment]
> `org_img` is empty. Check your image path



> `org_img`是空的。检查您的图像路径

I didn't understand that org_img is empty, same problem as his after training 30EPOCH.  I just put 10% of train in test. TXT, then how do I build org_img

**Comment by xaioffff** [comment]
> 我不明白org_img是空的，训练30EPOCH后和他的问题一样。我只是测试了 10% 的火车。TXT，那我怎么建org_img

我不明白org_img是空的，训练30EPOCH后和他的问题一样。我只是测试了 10% 的火车。TXT，那我怎么建org_img
