### ISSUE TITLE
与原作者的对比可以写一下么

### ISSUE THREAD

**Issue by mengfanda** [argusswift/YOLOv4-pytorch#20]
请问一下，作者可以写一下复现版本和原作者的COCO测试集的map、速度等指标的对比么？这样也可以了解整个复现版本是否到达了原作者相同水平

**Comment by argusswift** [comment]
> 请问一下，作者可以写一下复现版本和原作者的COCO测试集的map、速度等指标的对比么？这样也可以了解整个复现版本是否到达了原作者相同水平

好的。具体内容会在后面更新。
