### ISSUE TITLE
CUDA OUT OF MEMORY

### ISSUE THREAD

**Issue by feng-ai** [argusswift/YOLOv4-pytorch#222]
I tried many methods, such as adjusting batch_ size, but still oom. In fact, my machine memory is 64g and my video memory is 11g. Batch should not appear batch_ size cannot be set more than 16. And bacth_size is reduced, oom will also appear after running several epochs. How to solve it?

**Comment by EdwardLocke** [comment]
> 我尝试了很多方法，例如调整batch_size，但仍然是oom。其实我的机器内存是64g，显存是11g。批处理不应出现batch_size不能设置大于16。而且bacth_size减小了，运行几个epochs后也会出现oom。如何解决？

Hello, I also encountered the same problem, have you solved it?

**Comment by EdwardLocke** [comment]
> I tried many methods, such as adjusting batch_ size, but still oom. In fact, my machine memory is 64g and my video memory is 11g. Batch should not appear batch_ size cannot be set more than 16. And bacth_size is reduced, oom will also appear after running several epochs. How to solve it?

Hello, I also encountered the same problem, have you solved it?

**Comment by feng-ai** [comment]
Not yet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
