### ISSUE TITLE
attention machnism

### ISSUE THREAD

**Issue by life97** [argusswift/YOLOv4-pytorch#223]
你好，很感谢这个仓库，提供这么好的源码有机会来学习，已经将仓库的训练文件能够调通了，想请教下在代码中我看是在CSPblock中加入了注意力机制，请问这样需要加载YOLOV4的预训练后还需要在ImageNet上重新训练吗？我看完源码后的理解就是加载YOLOV4的预训练训练加入注意力机制后的模型？如果你能回复的话，万分感激~

**Comment by argusswift** [comment]
> 

最好是修改了主干网络后，放在大型分类数据集（比如ImageNet）上去pre-training，这样在后面训练整个YOLO会fine-tune更快，更大概率收敛到全局最小，当然得出的结果也便是最好的。省去pre-training的过程则需要你计算机的算力更强，batch更大，以便在每个feed的过程让网络看到更多的信息，加深数据理解。

**Comment by life97** [comment]
> > 
> 
> 最好是修改了主干网络后，放在大型分类数据集（比如ImageNet）上去pre-training，这样在后面训练整个YOLO会fine-tune更快，更大概率收敛到全局最小，当然得出的结果也便是最好的。省去pre-training的过程则需要你计算机的算力更强，batch更大，以便在每个feed的过程让网络看到更多的信息，加深数据理解。

好的，明白，感谢你的耐心解答~
