### ISSUE TITLE
关于CBAM的问题

### ISSUE THREAD

**Issue by achel-x** [argusswift/YOLOv4-pytorch#240]
您好，我最近也需要在YOLOv3中插入CBAM，但是效果并不佳，我看到您的代码中也加入了CBAM部分的代码，并且取得了提升，所以冒昧的想请教几个问题
1、请问您的CBAM插在哪个位置，我这边的结果显示在backbone插入的效果没有在neck和head的好，但是都低于没有插入的时候，我这边没有插入的时候，在VOC2007上的mAP大约是83.2左右，插入后都在82左右。就很奇怪
2、请问您的训练是否使用了预训练模型

**Comment by argusswift** [comment]
> 您好，我最近也需要在YOLOv3中插入CBAM，但是效果并不佳，我看到您的代码中也加入了CBAM部分的代码，并且取得了提升，所以冒昧的想请教几个问题 1、请问您的CBAM插在哪个位置，我这边的结果显示在backbone插入的效果没有在neck和head的好，但是都低于没有插入的时候，我这边没有插入的时候，在VOC2007上的mAP大约是83.2左右，插入后都在82左右。就很奇怪 2、请问您的训练是否使用了预训练模型

1.我是在残差块里加入CBAM
2.我先在imagenet上预训练了backbone

**Comment by DreamYH** [comment]
> > 您好，我最近也需要在YOLOv3中插入CBAM，但是效果并不佳，我看到您的代码中也加入了CBAM部分的代码，并且取得了提升，所以冒昧的想请教几个问题 1、请问您的CBAM插在哪个位置，我这边的结果显示在backbone插入的效果没有在neck和head的好，但是都低于没有插入的时候，我这边没有插入的时候，在VOC2007上的mAP大约是83.2左右，插入后都在82左右。就很奇怪 2、请问您的训练是否使用了预训练模型
> 
> 1.我是在残差块里加入CBAM 2.我先在imagenet上预训练了backbone

你好，请问方便提供您使用CBAM时候用的，预训练权重么，我使用了CBAM用的还是以前的预训练权重，模型性能下降了，看问题，您说需要在imagenet上预训练然后在finetune，您有能够使用CBAM的预训练权重么，可以发我一份么，liyuewei0901@163.com，方便的话可以发一下么，谢谢
