### ISSUE TITLE
工程里面数据增强模块用的是mixup，是否尝试过原作的mosaic

### ISSUE THREAD

**Issue by hujunchao** [argusswift/YOLOv4-pytorch#31]
非常感谢作者的分享！有个问题想要请教你，工程里面数据增强模块用的是mixup，是否尝试过论文里面的mosaic

**Comment by argusswift** [comment]
> 非常感谢作者的分享！有个问题想要请教你，工程里面数据增强模块用的是mixup，是否尝试过论文里面的mosaic

正在尝试，代码将在稍后更新
