### ISSUE TITLE
i have a question . where to add cbam model in yolov4 ？

### ISSUE THREAD

**Issue by Alex-afka** [argusswift/YOLOv4-pytorch#32]

**Comment by argusswift** [comment]
> _No description provided._

In the residual of CSPdarknet53

**Comment by Alex-afka** [comment]
it is in bottleneckcsp ？  i want to know the details about cbam  because i used it in my model
but it has no effect . i add cbam in the last of cspdarknet . thank you .

**Comment by argusswift** [comment]
> it is in bottleneckcsp ？ i want to know the details about cbam because i used it in my model
> but it has no effect . i add cbam in the last of cspdarknet . thank you .

sure，it was added into bottlenecks of CSPdarknet53 certainly.Since there is no pre-training weight of CBAM-CSPdarknet, it is difficult to fit your own data set. Therefore, I suggest that you are supposed to use CBAM-CSPdarknet pre-training weight in Yolov4 after it has been pre-trained on Imagenet.

**Comment by Alex-afka** [comment]
thank you .i think add the cbam will be better for model.  in your working you use the pre-trained in cbam-cspdarknet?

**Comment by argusswift** [comment]
> use the pre-trained in cbam-cspdarknet

In my work, I had not used the pre-trained in cbam-cspdarknet weight. I just provide an idea for you to be referenced. Of course, if you are interested in this work, you could pre-train cbam-cspdarknet in Imagenet.

**Comment by Alex-afka** [comment]
thank you for your working . really thank you ! i add your qq  .

**Comment by sakurasakura1996** [comment]
if you pre-train cbam-cspdarknet in imagenet,can you support the pre-trained weights, My computer is low 😂
