### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by yishunzhijian** [argusswift/YOLOv4-pytorch#34]
请问训练时出现这个会影响训练结果吗？
val img size is 416
 82%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 317/387 [00:32<00:07,  9.16it/s]Corrupt JPEG data: 1 extraneous bytes before marker 0xdb
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 387/387 [00:40<00:00,  9.57it/s]

**Comment by argusswift** [comment]
> 请问训练时出现这个会影响训练结果吗？
> val img size is 416
> 82%|████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 317/387 [00:32<00:07, 9.16it/s]Corrupt JPEG data: 1 extraneous bytes before marker 0xdb
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 387/387 [00:40<00:00, 9.57it/s]

这是使用opencv(python)读取图片时，由于图片破损等情况，读取的信息不完整导致的。基本不影响实验结果

**Comment by yishunzhijian** [comment]
谢谢，还有就是训练自己数据集150epoch之后，结果比darknet版本效果差很多

**Comment by yishunzhijian** [comment]
还有一个问题，测试自己的图片时为什么没有类别显示？

**Comment by argusswift** [comment]
> 谢谢，还有就是训练自己数据集150epoch之后，结果比darknet版本效果差很多

是加载了预训练模型后训练的结果差嘛

**Comment by yishunzhijian** [comment]
> > 谢谢，还有就是训练自己数据集150epoch之后，结果比darknet版本效果差很多
> 
> 是加载了预训练模型后训练的结果差嘛

是的，加载yolov4.weight权重

**Comment by argusswift** [comment]
> > > 谢谢，还有就是训练自己数据集150epoch之后，结果比darknet版本效果差很多
> > 
> > 
> > 是加载了预训练模型后训练的结果差嘛
> 
> 是的，加载yolov4.weight权重。请问你的do conv用在哪里了？为什么还可以加载yolov4预训练模型，而没有出现维度不匹配的问题

暂时没有将do conv添加到网络当中。

**Comment by yishunzhijian** [comment]
> 暂时没有将do conv添加到网络当中。

我看你的Brief里面有do conv

**Comment by argusswift** [comment]
> > 暂时没有将do conv添加到网络当中。
> 
> 我看你的Brief里面有do conv

你可以自己试一下将do conv替换原始的卷积核，只不过不能加载预训练模型。
