### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by wdings** [argusswift/YOLOv4-pytorch#37]
请问前面这组anchor和后面注释的anchor是怎样的尺度关系？
MODEL = {"ANCHORS":[[(1.25, 1.625), (2.0, 3.75), (4.125, 2.875)],       # Anchors for small obj(12,16),(19,36),(40,28)
            [(1.875, 3.8125), (3.875, 2.8125), (3.6875, 7.4375)],                  # Anchors for medium obj(36,75),(76,55),(72,146)
            [(3.625, 2.8125), (4.875, 6.1875), (11.65625, 10.1875)]],          # Anchors for big obj(142,110),(192,243),(459,401)
         "STRIDES":[8, 16, 32],
         "ANCHORS_PER_SCLAE":3
         }

**Comment by argusswift** [comment]
> 请问前面这组anchor和后面注释的anchor是怎样的尺度关系？
> MODEL = {"ANCHORS":[[(1.25, 1.625), (2.0, 3.75), (4.125, 2.875)], # Anchors for small obj(12,16),(19,36),(40,28)
> [(1.875, 3.8125), (3.875, 2.8125), (3.6875, 7.4375)], # Anchors for medium obj(36,75),(76,55),(72,146)
> [(3.625, 2.8125), (4.875, 6.1875), (11.65625, 10.1875)]], # Anchors for big obj(142,110),(192,243),(459,401)
> "STRIDES":[8, 16, 32],
> "ANCHORS_PER_SCLAE":3
> }

这是我标注时的错误，真实聚类框是我根据我的数据样本生成的。ANCHORS乘以每个尺度的STRIDES就得到真实的锚框。
