### ISSUE TITLE
coco数据集装成voc后没有ImageSets

### ISSUE THREAD

**Issue by mathpopo** [argusswift/YOLOv4-pytorch#42]
classes = cfg.COCO_DATA["CLASSES"]
    img_inds_file = os.path.join(
        data_path, "ImageSets", "Main", file_type + ".txt"
    )

**Comment by argusswift** [comment]
> ```
> classes = cfg.COCO_DATA["CLASSES"]
> img_inds_file = os.path.join(
>     data_path, "ImageSets", "Main", file_type + ".txt"
> )
> ```

你可以自己创建目录ImageSets/Main/，下面放train.txt和test.txt文件。

**Comment by mathpopo** [comment]
好的，谢谢。
