### ISSUE TITLE
there is something wrong with voc.py

### ISSUE THREAD

**Issue by xuguosheng110** [argusswift/YOLOv4-pytorch#43]
you forget the class_id of classes

img_inds_file = os.path.join(data_path, 'ImageSets', 'Main', class_id+'_'+file_type+'.txt')

**Comment by argusswift** [comment]
> you forget the class_id of classes
> 
> img_inds_file = os.path.join(data_path, 'ImageSets', 'Main', class_id+'_'+file_type+'.txt')

Please tell me which file and line of your issue
