### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by yishunzhijian** [argusswift/YOLOv4-pytorch#45]
请问用自己的数据集训练，测试自己的图片时为什么不显示类别？

**Comment by argusswift** [comment]
> 请问用自己的数据集训练，测试自己的图片时为什么不显示类别？

我不知道怎么解决你的问题，请把图片贴出来，谢谢

**Comment by yishunzhijian** [comment]
> > 请问用自己的数据集训练，测试自己的图片时为什么不显示类别？
> 
> 我不知道怎么解决你的问题，请把图片贴出来，谢谢
![000157](https://user-images.githubusercontent.com/59228486/95998625-a0f89c80-0e67-11eb-96a9-269edc55ad57.jpg)

**Comment by argusswift** [comment]
> > > 请问用自己的数据集训练，测试自己的图片时为什么不显示类别？
> > 
> > 
> > 我不知道怎么解决你的问题，请把图片贴出来，谢谢
> > ![000157](https://user-images.githubusercontent.com/59228486/95998625-a0f89c80-0e67-11eb-96a9-269edc55ad57.jpg)

收到您的反馈，我们将代码修正好了并上传。感谢指出
