### ISSUE TITLE
To visualize heatmaps,and something wrong.

### ISSUE THREAD

**Issue by haobabuhaoba** [argusswift/YOLOv4-pytorch#48]
`python eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual $DATA_TEST --eval`
FOR m:I change the $DATA_TEST,and don't see the heatmaps whinch in the output,it start eval ,so does this command correct?

**Comment by argusswift** [comment]
> `python eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual $DATA_TEST --eval`
> FOR m:I change the $DATA_TEST,and don't see the heatmaps whinch in the output,it start eval ,so does this command correct?

Heatmap only works in Attention. Set Showatt = true before running eval_VOC.py

**Comment by xaioffff** [comment]
> > `python eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual $DATA_TEST --eval`
> > FOR m：我更改了 $DATA_TEST，在输出中看不到热图，它开始 eval ，所以这个命令正确吗？
> 
> 热图仅适用于注意力。在运行 eval_VOC.py 之前设置 Showatt = true
![image](https://user-images.githubusercontent.com/92706955/147234540-7ffdede1-953c-4a95-8307-4af0037860f1.png)
请问热力图这个怎么解决呀

**Comment by xaioffff** [comment]
> 热图仅适用于注意力。在运行 eval_VOC.py 之前设置 Showatt = true

请问解决了吗
