### ISSUE TITLE
Mobilenet model access

### ISSUE THREAD

**Issue by chaiban** [argusswift/YOLOv4-pytorch#49]
Hi @argusswift ,

Thank you for the wonderful code. I am not able to download the mobilenet weights, can you please share them via onedrive or google drive ? 

The network is working fine with yolo v4 weights but it runs with 15 fps. May be mobilenet could improve the test speed. 

Thank you!

**Comment by argusswift** [comment]
> Hi @argusswift ,
> 
> Thank you for the wonderful code. I am not able to download the mobilenet weights, can you please share them via onedrive or google drive ?
> 
> The network is working fine with yolo v4 weights but it runs with 15 fps. May be mobilenet could improve the test speed.
> 
> Thank you!

What is the configuration of your computer.

**Comment by chaiban** [comment]
I am running it on RTX 2060S - 8GB memory

**Comment by argusswift** [comment]
> I am running it on RTX 2060S - 8GB memory
> CPU= i5-8thgen 16 GB RAM

You can use following link:(mobilenetv2)https://github.com/d-li14/mobilenetv2.pytorch/blob/master/pretrained/mobilenetv2_1.0-0c6065bc.pth

**Comment by chaiban** [comment]
Thank you so much
