### ISSUE TITLE
Problem of reloading last.pt

### ISSUE THREAD

**Issue by vincent9619** [argusswift/YOLOv4-pytorch#5]
When I want to keep training with last.pt, during the training, it came out: 
[2020-08-17 16:24:16,601]-[train.py line:153]:  === Epoch:[  0/301],step:[  0/355],img_size:[416],total_loss:nan|loss_giou:nan|loss_conf:nan|loss_cls:nan|lr:0.0000 
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.

Still, I can't run the program with gpu, I tried to change the gpu_id but it doesn't work.

Please help me. Thank you!

**Comment by The-OldWang** [comment]
> 当我想继续使用last.pt进行训练时，在训练过程中它出来了：
> [2020-08-17 16：24：16,601]-[train.py line：153]：===时期：[0/301 ]，step：[0/355]，img_size：[416]，total_loss：nan | loss_giou：nan | loss_conf：nan | loss_cls：nan | lr：0.0000
> 警告：在输入张量中找到root：NaN或Inf。
> 警告：在输入张量中找到root：NaN或Inf。
> 警告：在输入张量中找到root：NaN或Inf。
> 
> 不过，我无法使用gpu运行该程序，我试图更改gpu_id，但它不起作用。
> 
> 请帮我。谢谢！
Hello, I encountered the same problem as you, have you solved it？

**Comment by argusswift** [comment]
> > 当我想继续使用last.pt进行训练时，在训练过程中它出来了：
> > [2020-08-17 16：24：16,601]-[train.py line：153]：===时期：[0/301 ]，step：[0/355]，img_size：[416]，total_loss：nan | loss_giou：nan | loss_conf：nan | loss_cls：nan | lr：0.0000
> > 警告：在输入张量中找到root：NaN或Inf。
> > 警告：在输入张量中找到root：NaN或Inf。
> > 警告：在输入张量中找到root：NaN或Inf。
> > 不过，我无法使用gpu运行该程序，我试图更改gpu_id，但它不起作用。
> > 请帮我。谢谢！
> > Hello, I encountered the same problem as you, have you solved it？

这是现阶段学习率太大导致的。请检查优化器和epoch参数是否正确加载。

**Comment by EternalEvan** [comment]
可以说说你是怎么解决这个问题的吗，十分感谢！！！
