### ISSUE TITLE
training error, dimention is not match

### ISSUE THREAD

**Issue by hailuo0112** [argusswift/YOLOv4-pytorch#53]
![2020-10-20 15-31-24 的屏幕截图](https://user-images.githubusercontent.com/1246018/96554723-7e440900-12e9-11eb-9010-a142aae6651d.png)

**Comment by argusswift** [comment]
这是训练中途出现的问题，应该是你的数据有点问题。请检查一下你的数据格式是否正确。

**Comment by hailuo0112** [comment]
> 这是训练中途出现的问题，应该是你的数据有点问题。请检查一下你的数据格式是否正确。

Q1：训练数据格式是【name.jpg x1,y1,x2,y2,cls_id 】还是【name.jpg center_x,center_y,w,h,cls_id】?是这两者中的哪一者？
Q2：是否都是要归一化后的（如果不改动工程任何loss之类的前提下）？

**Comment by argusswift** [comment]
> > 这是训练中途出现的问题，应该是你的数据有点问题。请检查一下你的数据格式是否正确。
> 
> Q1：训练数据格式是【name.jpg x1,y1,x2,y2,cls_id 】还是【name.jpg center_x,center_y,w,h,cls_id】?是这两者中的哪一者？
> Q2：是否都是要归一化后的（如果不改动工程任何loss之类的前提下）？

Q1：后者
Q2：不需要归一化，程序内部有归一化的过程
