### ISSUE TITLE
请问代码中使用dropblock吗？

### ISSUE THREAD

**Issue by xiaozhangya** [argusswift/YOLOv4-pytorch#55]
请问代码中使用dropblock吗？

**Comment by argusswift** [comment]
> 请问代码中使用dropblock吗？

是那个地方需要dropblock模块呢

**Comment by xiaozhangya** [comment]
> > 请问代码中使用dropblock吗？
> 
> 是那个地方需要dropblock模块呢

原始yolov4论文不是使用了吗？？你在那使用了？

**Comment by argusswift** [comment]
> > > 请问代码中使用dropblock吗？
> > 
> > 
> > 是那个地方需要dropblock模块呢
> 
> 原始yolov4论文不是使用了吗？？你在那使用了？

暂时没有在这个repo使用dropblock
