### ISSUE TITLE
How about adding this parameter used int yolov4 ?

### ISSUE THREAD

**Issue by HaolyShiit** [argusswift/YOLOv4-pytorch#59]
https://github.com/AlexeyAB/darknet/blob/8297b1be3108f47d82b97d322d5f1aef5150018f/src/yolo_layer.c#L354

In yolov4, a scale (offset) parameter is applied in predicted center of bbox as shown above.
Could  you try this ?

**Comment by argusswift** [comment]
> https://github.com/AlexeyAB/darknet/blob/8297b1be3108f47d82b97d322d5f1aef5150018f/src/yolo_layer.c#L354
> 
> In yolov4, a scale (offset) parameter is applied in predicted center of bbox as shown above.
> Could you try this ?

No.I haven't.It will take me a lot of time and energy to do such a thing
