### ISSUE TITLE
About the method of anchors of customer dataset?

### ISSUE THREAD

**Issue by JackHenry1992** [argusswift/YOLOv4-pytorch#6]
Thank you for sharing your code. Can you share the method for calculating the anchors of self-dataset?

**Comment by argusswift** [comment]
> Thank you for sharing your code. Can you share the method for calculating the anchors of self-dataset?

I have uploaded a file (utils/kmeans.py), which could generate anchors using kmeans method.

**Comment by JackHenry1992** [comment]
![image](https://user-images.githubusercontent.com/9390228/92068257-0e310080-edd9-11ea-935d-32b5b22b85ff.png)
How about the relationship between these two anchors ？ By using your scripts， I only get the right one with integer elements。
