### ISSUE TITLE
训练自己数据时出现loss=nan

### ISSUE THREAD

**Issue by luocmin** [argusswift/YOLOv4-pytorch#62]
训练一段时间loss=nan，验证时map都为0，请问是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/57932842/97272038-5108d500-186c-11eb-9175-9e67a75eeb19.png)

![image](https://user-images.githubusercontent.com/57932842/97271981-3e8e9b80-186c-11eb-845a-4c5fbb72cfa1.png)

**Comment by argusswift** [comment]
> 训练一段时间loss=nan，验证时map都为0，请问是什么原因导致的呢？
> ![image](https://user-images.githubusercontent.com/57932842/97272038-5108d500-186c-11eb-9175-9e67a75eeb19.png)
> 
> ![image](https://user-images.githubusercontent.com/57932842/97271981-3e8e9b80-186c-11eb-845a-4c5fbb72cfa1.png)

请检查一下输入的图片和标注是否正确，或者是调小初始学习率。

**Comment by jingtianyilong** [comment]
Large LR Large accumulate might be the cause. But I also notice that you got inf in the input tensor, which should definately not supposed to happen. Check your dataloader

**Comment by argusswift** [comment]
> Large LR Large accumulate might be the cause. But I also notice that you got `inf` in the input tensor, which is definately not supposed to happen. Check your dataloader

We share consistent idea.

**Comment by jinfagang** [comment]
the warning message got `inf input  tensorrtt` doesn't means the input data is Nan. Some tensor got Nan, mostly because of lr too big
