### ISSUE TITLE
加载自己的数据集出错

### ISSUE THREAD

**Issue by zjnlxk** [argusswift/YOLOv4-pytorch#63]
![image](https://user-images.githubusercontent.com/63961323/97388732-a64bf180-1913-11eb-9ee1-84a6842134b9.png)

**Comment by zjnlxk** [comment]
![image](https://user-images.githubusercontent.com/63961323/97389515-71d93500-1915-11eb-9a89-6fe867269f16.png)
z这一段代码不是很理解，想请教一下？

**Comment by jingtianyilong** [comment]
-1 means depends on the other parameter.
example:
a (1,12) matrix can be reshaped as (3,4) with reshape(3,-1) or (-1,4)

**Comment by argusswift** [comment]
> this is only a demo for you to test if the dataset module works well. It uses voc as the data source. 26 basically means 20(class number)+6(x y h w conf objectness)?
> reshape(-1,26) just means reshape the label input to (number_of_bbox, 26). -1 is what makes it adaptive.
> `sbbox`, `mbbox`, `lbbox` was relative description in compare to the corresponding anchor box.

Thanks for you reply.

**Comment by argusswift** [comment]
> ![image](https://user-images.githubusercontent.com/63961323/97389515-71d93500-1915-11eb-9a89-6fe867269f16.png)
> z这一段代码不是很理解，想请教一下？

具体可以看
https://github.com/argusswift/YOLOv4-pytorch/blob/c9b1093ed5ad2e5375c5f0ec9086ea121fd33d03/utils/datasets.py#L142

**Comment by zjnlxk** [comment]
THANKS FOR YOU REPLY
