### ISSUE TITLE
mobilenetv2_yolov4,训练了120epoch，在VOC2007test上的map只有72.6%？

### ISSUE THREAD

**Issue by yuerunyu** [argusswift/YOLOv4-pytorch#64]
使用readme中提供的mobilenetv2_yolov4.pth，可以达到map值为85.1%。请问您是训练了多少轮？
我只是按照readme中对yolo_config中的对应位置进行修改，其余的参数没有改变。

**Comment by jingtianyilong** [comment]
try with more epoch. I found out that 250~300 would be a good choice for my custom dataset. Not sure about VOC.

**Comment by yuerunyu** [comment]
@jingtianyilong ,thank you,I will try more epoch.

**Comment by cangwang** [comment]
hello，为何我使用mobilenetv3和只用voc2007训练，最后只有0.178%的mAp

**Comment by yuerunyu** [comment]
@cangwang 我使用的是VOC2007+VOC2012的trainval训练的，得到了map=72.6%。可能是你训练数据太少了，过拟合了。

**Comment by cangwang** [comment]
应该不少啊，voc2007训练集也有5000张，应该不会过拟合。你是用了他的预训练集，还是自己重头训练？

**Comment by cangwang** [comment]
这个框架有QQ讨论群吗？

**Comment by yuerunyu** [comment]
@cangwang 自己重头训练的

**Comment by cangwang** [comment]
大佬，可以加一下你的QQ吗？

**Comment by argusswift** [comment]
> 使用readme中提供的mobilenetv2_yolov4.pth，可以达到map值为85.1%。请问您是训练了多少轮？
> 我只是按照readme中对yolo_config中的对应位置进行修改，其余的参数没有改变。

请问使用了预训练模型了吗

**Comment by argusswift** [comment]
> try with more epoch. I found out that 250~300 would be a good choice for my custom dataset. Not sure about VOC.

Well done,thank you for your reply.Maybe your tips will work.

**Comment by yuerunyu** [comment]
@argusswift 使用的预训练模型是mobilenetv2，然后在voc2007+vco2012的trainval数据上进行了120epoch的训练，得到的map是72.6%，使用readme提供的mobilev2_yolov4.pth得到的map是85.1%，所以想知道你当时训练的时候，也是120epoch吗？还是更多？

**Comment by jinfagang** [comment]
I traind 200 epochs, loss still very high: about 5

**Comment by cangwang** [comment]
@yuerunyu 我使用了voc2007 和voc2012 两个数据集使用了yolov4-mobilenet一起训练了200个epoch，发现还是mAp还是上不去
![image](https://user-images.githubusercontent.com/10419150/97823003-960c8b80-1cf2-11eb-84a2-07a84e2512b0.png)
你那边backbone是使用哪个？是否有用yolov4-mobilenet？

**Comment by yuerunyu** [comment]
@cangwang 使用的是mobilenetv2的预训练模型。

**Comment by Imagery007** [comment]
请问增加epoch提升到作者的map吗，我尝试260个epoch，map依然在七十多
