### ISSUE TITLE
训练后模型的大小问题

### ISSUE THREAD

**Issue by jichaoqun** [argusswift/YOLOv4-pytorch#65]
我使用mobeilenet-yolo训练的模型，得到的结果里除了best.pt为116M左右，其余的都是232M,这是正常的现象吗？最后的模型就这么大吗？

**Comment by argusswift** [comment]
> 我使用mobeilenet-yolo训练的模型，得到的结果里除了best.pt为116M左右，其余的都是232M,这是正常的现象吗？最后的模型就这么大吗？

best.pt包含网络权重，而其他的文件不仅包含网络部分，也包含优化器，best_mAP,epoch等参数。

**Comment by jinfagang** [comment]
@argusswift mobilenetv3 的yolov5权重只有6M

**Comment by argusswift** [comment]
> @argusswift mobilenetv3 的yolov5权重只有6M

请把链接发一下，我学习一下。谢谢

**Comment by 2696120622** [comment]
@jichaoqun 我也是Mobilenet-YOLOv4，186M，是哪个模块增加了这么多权重？
