### ISSUE TITLE
基于给出的voc_best.pt的错误

### ISSUE THREAD

**Issue by Jayefo** [argusswift/YOLOv4-pytorch#67]
Traceback (most recent call last):
  File "eval_voc.py", line 113, in <module>
    visiual=opt.visiual).detection()
  File "eval_voc.py", line 34, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 43, in __load_model_weights
    self.__model.load_state_dict(chkpt)
  File "C:\Anaconda3\envs\YOLOv4-pytorch\lib\site-packages\torch\nn\modules\module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Build_Model:

**Comment by Jayefo** [comment]
RuntimeError: Error(s) in loading state_dict for Build_Model:
        Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",

**Comment by Jayefo** [comment]
这个问题是为啥啊，self.__model.load_state_dict(chkpt, False)，加了false还是不行

**Comment by Jayefo** [comment]
size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.0.weight: copying a param with shape torch.Size([640, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).

**Comment by argusswift** [comment]
> RuntimeError: Error(s) in loading state_dict for Build_Model:
> Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",

你用的是mobilenet的网络，加载的却是darknet的模型

**Comment by Jayefo** [comment]
您能方便告诉我在那个文件里边修改吗，是那个config里边吗，谢谢，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argusswift/YOLOv4-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 中午11:19
收件人:&nbsp;"argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"佛计"<1754208529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [argusswift/YOLOv4-pytorch] 基于给出的voc_best.pt的错误 (#67)





  
RuntimeError: Error(s) in loading state_dict for Build_Model:
 Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",
  
你用的是mobilenet的网络，加载的却是darknet的模型

**Comment by Jayefo** [comment]
是不是只要下载一个darknet的预训练网络就行了

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argusswift/YOLOv4-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 中午11:19
收件人:&nbsp;"argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"佛计"<1754208529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [argusswift/YOLOv4-pytorch] 基于给出的voc_best.pt的错误 (#67)





  
RuntimeError: Error(s) in loading state_dict for Build_Model:
 Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",
  
你用的是mobilenet的网络，加载的却是darknet的模型

**Comment by Jayefo** [comment]
我加载的模型是voc_best.pt








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argusswift/YOLOv4-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 中午11:19
收件人:&nbsp;"argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"佛计"<1754208529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [argusswift/YOLOv4-pytorch] 基于给出的voc_best.pt的错误 (#67)





  
RuntimeError: Error(s) in loading state_dict for Build_Model:
 Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",
  
你用的是mobilenet的网络，加载的却是darknet的模型

**Comment by Jayefo** [comment]
我用的是这个模型的连接



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "argusswift/YOLOv4-pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月1日(星期天) 中午11:19
收件人:&nbsp;"argusswift/YOLOv4-pytorch"<YOLOv4-pytorch@noreply.github.com&gt;;
抄送:&nbsp;"佛计"<1754208529@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [argusswift/YOLOv4-pytorch] 基于给出的voc_best.pt的错误 (#67)





  
RuntimeError: Error(s) in loading state_dict for Build_Model:
 Missing key(s) in state_dict: "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.0.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.weight", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.bias", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_mean", "_Build_Model__yolov4.backbone._MobilenetV3__submodule.features.0.1.running_var",
  
你用的是mobilenet的网络，加载的却是darknet的模型

**Comment by Jayefo** [comment]
![Uploading image.png…]()

**Comment by Jayefo** [comment]
size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.0.weight: copying a param with shape torch.Size([640, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.1.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.1.running_mean: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.0.conv.1.running_var: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.1.conv.0.weight: copying a param with shape torch.Size([1280, 640, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 512, 3, 3]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.1.conv.1.weight: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.1.conv.1.bias: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.1.conv.1.running_mean: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.1.conv.1.running_var: copying a param with shape torch.Size([1280]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.2.conv.0.weight: copying a param with shape torch.Size([640, 1280, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.2.conv.1.weight: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.2.conv.1.bias: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.2.conv.1.running_mean: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.spp.head_conv.2.conv.1.running_var: copying a param with shape torch.Size([640]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform3.conv.0.weight: copying a param with shape torch.Size([16, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 1, 1]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform3.conv.1.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform3.conv.1.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform3.conv.1.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform3.conv.1.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform4.conv.0.weight: copying a param with shape torch.Size([48, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform4.conv.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform4.conv.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform4.conv.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.feature_transform4.conv.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.resample5_4.upsample.0.conv.0.weight: copying a param with shape torch.Size([48, 640, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
	size mismatch for _Build_Model__yolov4.panet.resample5_4.upsample.0.conv.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.resample5_4.upsample.0.conv.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.resample5_4.upsample.0.conv.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.resample5_4.upsample.0.conv.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for _Build_Model__yolov4.panet.resample4_3.upsample.0.conv.0.weight: copying a param with shape torch.Size([16, 48, 1, 1]) from checkpoint,

**Comment by Jayefo** [comment]
我这里采用的pt文件是voc_best.pt，并且将yolov4_config.py里边的模型修改为YOLOV4，但是最后的结果还是会报出上述不匹配的错误，您能给出一些提示吗？

**Comment by argusswift** [comment]
> 我这里采用的pt文件是voc_best.pt，并且将yolov4_config.py里边的模型修改为YOLOV4，但是最后的结果还是会报出上述不匹配的错误，您能给出一些提示吗？

将yolov4_config.py里边的模型修改为Mobilenet-YOLOv4.因为你加载的是Mobilenet-YOLOv4的训练权重
