### ISSUE TITLE
计算损失时出错

### ISSUE THREAD

**Issue by zjnlxk** [argusswift/YOLOv4-pytorch#72]
![image](https://user-images.githubusercontent.com/63961323/97966067-4616ed00-1df6-11eb-93f7-443c5ec85f87.png)
w
我的类别是6类，不知道这里是因为图片的问题还是参数的问题，希望大家指点一下

**Comment by zjnlxk** [comment]
![image](https://user-images.githubusercontent.com/63961323/97966831-51b6e380-1df7-11eb-9835-005e6e472326.png)
![Uploading image.png…]()

**Comment by argusswift** [comment]
> ![image](https://user-images.githubusercontent.com/63961323/97966067-4616ed00-1df6-11eb-93f7-443c5ec85f87.png)
> w
> 我的类别是6类，不知道这里是因为图片的问题还是参数的问题，希望大家指点一下

首先请检查yolov4_config.py里的类别数是你数据集的类别数，其次检查生成的train_annotation.txt里的类别是否有超出类别数的标签

**Comment by zjnlxk** [comment]
谢谢您的解答

**Comment by zjnlxk** [comment]
我在检查了cfg.py以及train_annotation.txt后，没有发现错误。boxes1是[1,52,52,3]但是boxes2是[1,72,72,3]。我想知道boxes2中72是怎么计算出来的，希望能指点一下！

**Comment by cangwang** [comment]
应该不是类别，是你输入的图片大小的问题

**Comment by zjnlxk** [comment]
我是不是应该删除有问题的照片，因为我刚开始resize了输入图片

**Comment by zjnlxk** [comment]
![image](https://user-images.githubusercontent.com/63961323/98065710-0e5c8380-1e90-11eb-8d0a-ce7133f9c015.png)
我把多尺度训练改为False后，可以训练了，但这个学习率lr0.0000,这个正常么？

**Comment by cangwang** [comment]
你讲学习率的打印的精度在调小一点，现在是.4f,你设置显示.6f,就可以看到打印了。

**Comment by zjnlxk** [comment]
THANKS
