### ISSUE TITLE
训练过程中出错

### ISSUE THREAD

**Issue by zjnlxk** [argusswift/YOLOv4-pytorch#75]
![image](https://user-images.githubusercontent.com/63961323/98101430-27cff080-1ecd-11eb-9b4a-a129ef9cd8ea.png)
一直出现这个错误，训练了好几次了，我每次都把那些出错的图片删掉，不知道方法对不对，求指点！

**Comment by jingtianyilong** [comment]
Check your dataloader. Wrong path or broken image. Output the image path and image size to check if image has been read properly

**Comment by zjnlxk** [comment]
THANKS
