### ISSUE TITLE
请问一下总是报错说train_annotation.txt文件找不到，如何解决呢？

### ISSUE THREAD

**Issue by KittyGao-Cui** [argusswift/YOLOv4-pytorch#77]
在运行train.py文件时报错：FileNotFoundError: [Errno 2] No such file or directory: '/home/gaocui/Desktop/YOLOv4-pytorch/train_annotation.txt'。各位有遇到这个问题的吗，这个文件是从哪里下载或是如何生成的呢？

**Comment by shuang1204** [comment]
我也遇到了同样的问题，请问您解决了嘛？ @KittyGao-Cui
