### ISSUE TITLE
test的注释文件一定要用xml文件么？

### ISSUE THREAD

**Issue by zjnlxk** [argusswift/YOLOv4-pytorch#78]
我的test图片和train 图片的注释文件都是在txt文件里。我是需要把txt文件转换成xml文件么？
或者有没有其他的解决办法。
![image](https://user-images.githubusercontent.com/63961323/98354059-2f250480-205b-11eb-9da0-96134404f8cc.png)

**Comment by argusswift** [comment]
> 注释文件都是在txt文件

你的txt注释文件的格式是怎样的呢

**Comment by zjnlxk** [comment]
训练集和测试集一样，都是[图片路径+xmin,xmax,ymin,ymax,class]

**Comment by argusswift** [comment]
> 训练集和测试集一样，都是[图片路径+xmin,xmax,ymin,ymax,class]

那你测试的时候可能需要修改下程序了。测试的时候我加载数据的方式不是传统的dataloader，而是循环遍历。
