### ISSUE TITLE
开启热力图失败（设置eval_voc.py中的showatt=True）

### ISSUE THREAD

**Issue by wutiangreat** [argusswift/YOLOv4-pytorch#80]
测试图片会报错，如下：
raceback (most recent call last):
  File "eval_voc.py", line 110, in <module>
    Evaluation(gpu_id=opt.gpu_id,
  File "eval_voc.py", line 77, in detection
    bboxes_prd = self.__evalter.get_bbox(img,v)
  File "/home/dell/YOLOv4-pytorch/eval/evaluator.py", line 73, in get_bbox
    bboxes_list.append(self.__predict(img, test_input_size, valid_scale))
  File "/home/dell/YOLOv4-pytorch/eval/evaluator.py", line 94, in __predict
    if self.showatt: _, p_d, beta = self.model(img)
ValueError: not enough values to unpack (expected 3, got 2)
请问是缺少什么参数吗？我输入的命令是CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual ../img --eval --mode det 其中img是需要测试图片保存路径。

**Comment by April4lu** [comment]
请问这个问题是怎么解决的呢？

**Comment by shuang1204** [comment]
我也遇到了同样的问题，请问是如何解决的呀

**Comment by xaioffff** [comment]
> 测试图片会报错，如下： raceback (most recent call last): File "eval_voc.py", line 110, in Evaluation(gpu_id=opt.gpu_id, File "eval_voc.py", line 77, in detection bboxes_prd = self. __evalter.get_bbox(img,v) 文件“/home/dell/YOLOv4-pytorch/eval/evaluator.py”，第 73 行，在 get_bbox bboxes_list.append(self.__predict(img, test_input_size, valid_scale)) 文件“/home /dell/YOLOv4-pytorch/eval/evaluator.py”，第 94 行，在 __predict if self.showatt: _, p_d, beta = self.model(img) ValueError: 没有足够的值来解包（预期 3，得到 2） 我输入的命令是CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --visiual ../img --eval --mode det img是需要测试的吗？图片保存路径。



我也遇到了同样的问题，请问是如何解决的呀
