### ISSUE TITLE
训练时KeyError出错。

### ISSUE THREAD

**Issue by zjnlxk** [argusswift/YOLOv4-pytorch#83]
![image](https://user-images.githubusercontent.com/63961323/98764557-0748ee80-2417-11eb-962a-4eb54e0d19ca.png)
想问一下这里时因为照片找不到还是别的原因？我查看了路径以及注释文件，都是对的啊。
![image](https://user-images.githubusercontent.com/63961323/98764692-4d05b700-2417-11eb-8d8e-23777c313d73.png)
我debug后，image_ids里面是有这个图片的啊。希望大家指点一下。

**Comment by argusswift** [comment]
> ![image](https://user-images.githubusercontent.com/63961323/98764557-0748ee80-2417-11eb-962a-4eb54e0d19ca.png)
> 想问一下这里时因为照片找不到还是别的原因？我查看了路径以及注释文件，都是对的啊。
> ![image](https://user-images.githubusercontent.com/63961323/98764692-4d05b700-2417-11eb-8d8e-23777c313d73.png)
> 我debug后，image_ids里面是有这个图片的啊。希望大家指点一下。

你第二张图里面iamge_ids这个列表里文件名为1933.jpg的文件对应了两个索引（0001和0002）。检查一下你的测试数据是否正确。
