### ISSUE TITLE
coco.py里的一些疑惑

### ISSUE THREAD

**Issue by EternalEvan** [argusswift/YOLOv4-pytorch#84]
请问utils/coco.py里面用到的 cfg.DATA_PATH, "COCO2017_train", "VOCdevkit", "VOC2007" 和 data_path, "ImageSets", "Main", file_type + ".txt"这样的文件路径是coco数据集里面原本就有的吗？我找不到...请作者和大伙们指教一下呗，十分感谢！

**Comment by argusswift** [comment]
> 请问utils/coco.py里面用到的 cfg.DATA_PATH, "COCO2017_train", "VOCdevkit", "VOC2007" 和 data_path, "ImageSets", "Main", file_type + ".txt"这样的文件路径是coco数据集里面原本就有的吗？我找不到...请作者和大伙们指教一下呗，十分感谢！

这个是我转换后COCO数据集的路径，可以根据你自己的情况修改。
