### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by yinyuhangi** [argusswift/YOLOv4-pytorch#86]
您好，我给您的校园邮箱发了一封邮件，有些问题想请教一下，期待您的回复。

**Comment by argusswift** [comment]
> 您好，我给您的校园邮箱发了一封邮件，有些问题想请教一下，期待您的回复。

你好，我没有在校园邮箱收到关于您的邮件。请发邮件到3419923783@qq.com

**Comment by yinyuhangi** [comment]
@argusswift 已发到您的QQ邮箱，是否收到了呢？
