### ISSUE TITLE
训练过程中data_augment.py- Resize报错

### ISSUE THREAD

**Issue by Youjiangbaba** [argusswift/YOLOv4-pytorch#87]
`File "/home/jiang/Repositories/yolo系列/YOLOv4-pytorch-master/utils/datasets.py", line 116, in __parse_annotation
    np.copy(img), np.copy(bboxes)
  File "/home/jiang/Repositories/yolo系列/YOLOv4-pytorch-master/utils/data_augment.py", line 116, in __call__
    image_resized = cv2.resize(img, (resize_w, resize_h))
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4048: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'`

训练过程中，报错；然后调试输出 h_org, w_org, _ = img.shape，h_org, w_org=1，1080
图片是没问题的，不知道是否是datasets里面的数据处理部分有些问题。您如果有经验，希望能得到一些指导，找到问题所在。

我先加上判断异常进行训练
`    
def __parse_annotation(self, annotation):
        """
        Data augument.
        :param annotation: Image' path and bboxes' coordinates, categories.
        ex. [image_path xmin,ymin,xmax,ymax,class_ind xmin,ymin,xmax,ymax,class_ind ...]
        :return: Return the enhanced image and bboxes. bbox'shape is [xmin, ymin, xmax, ymax, class_ind]
        """
        anno = annotation.strip().split(" ")
        img_path = anno[0]
        img = cv2.imread(img_path)  # H*W*C and C=BGR
        im = img.copy()
        assert img is not None, "File Not Found " + img_path
        bboxes = np.array(
            [list(map(float, box.split(","))) for box in anno[1:]]
        )
        img, bboxes = dataAug.RandomHorizontalFilp()(
            np.copy(img), np.copy(bboxes), img_path
        )
        img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
        img, bboxes = dataAug.RandomAffine()(np.copy(img), np.copy(bboxes))

        #以上数据曾广有问题，可能会出现 1,h 的情况
        if img.shape[0] < 10 or img.shape[1] < 10:
            img = im.copy()
        img, bboxes = dataAug.Resize((self.img_size, self.img_size), True)(
            np.copy(img), np.copy(bboxes)
        )
        return img, bboxes
`

**Comment by argusswift** [comment]
> `File "/home/jiang/Repositories/yolo系列/YOLOv4-pytorch-master/utils/datasets.py", line 116, in __parse_annotation np.copy(img), np.copy(bboxes) File "/home/jiang/Repositories/yolo系列/YOLOv4-pytorch-master/utils/data_augment.py", line 116, in __call__ image_resized = cv2.resize(img, (resize_w, resize_h)) cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4048: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'`
> 
> 训练过程中，报错；然后调试输出 h_org, w_org, _ = img.shape，h_org, w_org=1，1080
> 图片是没问题的，不知道是否是datasets里面的数据处理部分有些问题。您如果有经验，希望能得到一些指导，找到问题所在。
> 
> 我先加上判断异常进行训练
> `
> def __parse_annotation(self, annotation):
> """
> Data augument.
> :param annotation: Image' path and bboxes' coordinates, categories.
> ex. [image_path xmin,ymin,xmax,ymax,class_ind xmin,ymin,xmax,ymax,class_ind ...]
> :return: Return the enhanced image and bboxes. bbox'shape is [xmin, ymin, xmax, ymax, class_ind]
> """
> anno = annotation.strip().split(" ")
> img_path = anno[0]
> img = cv2.imread(img_path) # H_W_C and C=BGR
> im = img.copy()
> assert img is not None, "File Not Found " + img_path
> bboxes = np.array(
> [list(map(float, box.split(","))) for box in anno[1:]]
> )
> img, bboxes = dataAug.RandomHorizontalFilp()(
> np.copy(img), np.copy(bboxes), img_path
> )
> img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> img, bboxes = dataAug.RandomAffine()(np.copy(img), np.copy(bboxes))
> 
> ```
>     #以上数据曾广有问题，可能会出现 1,h 的情况
>     if img.shape[0] < 10 or img.shape[1] < 10:
>         img = im.copy()
>     img, bboxes = dataAug.Resize((self.img_size, self.img_size), True)(
>         np.copy(img), np.copy(bboxes)
>     )
>     return img, bboxes
> ```
> 
> `

从你贴的程序上看，应该是程序没有读入数据，也可能是数据库和数据格式的问题。下面是我认为的两点原因：

1、自己的错误是数据库的图片数与程序中的图片数不同，所以报错。

2、数据库中图片后缀不匹配。

**Comment by Youjiangbaba** [comment]
出错了两次 一次在epoch2  一次是epoch8
应该数据读取没有问题吧？

**Comment by Youjiangbaba** [comment]
改成我贴的代码 也就是如果在数据增强后 某个通道值小于10  那就取原图进行您提供的resize方法
这样就顺利的训练完了120epoch

**Comment by argusswift** [comment]
> 改成我贴的代码 也就是如果在数据增强后 某个通道值小于10 那就取原图进行您提供的resize方法
> 这样就顺利的训练完了120epoch

很奇怪你的h_org和w_org会出现这种情况，可能你的数据图片的分辨率和一般的图片不太一样吧

**Comment by Youjiangbaba** [comment]
我的是1920x1080 标准的  
我用数据集试试您的 datasets.py和 data_augment.py ，看看能不能找到原因

**Comment by zjnlxk** [comment]
貌似数据集中图片的大小不一时，使用这个数据增强代码会出错。
