### ISSUE TITLE
Questions about heatmaps visualization

### ISSUE THREAD

**Issue by sjl623** [argusswift/YOLOv4-pytorch#9]
Thanks a lot for your work! However, when I try to visualize heatmaps after training, I got the error:

> Traceback (most recent call last):
  File "eval_coco.py", line 158, in <module>
    heatmap=opt.heatmap).Inference()
  File "eval_coco.py", line 117, in Inference
    bboxes_prd = self.__evalter.get_bbox(img, v)
  File "/root/CV/YOLOv4-pytorch-master/eval/evaluator.py", line 75, in get_bbox
    bboxes_list.append(self.__predict(img, test_input_size, valid_scale))
  File "/root/CV/YOLOv4-pytorch-master/eval/evaluator.py", line 97, in __predict
    if self.showatt: _,p_d,beta = self.model(img)
ValueError: not enough values to unpack (expected 3, got 2)

I run the command like this:
>  python eval_coco.py --gpu_id 0 --visiual output --mode det --heatmap True

Here are my config details:

>  MODEL_TYPE = {"TYPE": 'YOLOv4'}  #YOLO type:YOLOv4, Mobilenet-YOLOv4 or Mobilenetv3-YOLOv4
> 
> CONV_TYPE = {"TYPE": 'DO_CONV'}  #conv type:DO_CONV or GENERAL
> 
> ATTENTION = {"TYPE": 'CBAM'}  #6 
> 
> train
> TRAIN = {
>          "DATA_TYPE": 'COCO',  #DATA_TYPE: VOC or COCO
>          "TRAIN_IMG_SIZE": 416,
>          "AUGMENT": True,
>          "BATCH_SIZE": 4,
>          "MULTI_SCALE_TRAIN": False,
>          "IOU_THRESHOLD_LOSS": 0.5,
>          "YOLO_EPOCHS": 50,
>          "Mobilenet_YOLO_EPOCHS": 120,
>          "NUMBER_WORKERS": 0,
>          "MOMENTUM": 0.9,
>          "WEIGHT_DECAY": 0.0005,
>          "LR_INIT": 1e-4,
>          "LR_END": 1e-5,
>          "WARMUP_EPOCHS": 0  # or None
>          }
> 
> VAL = {
>         "TEST_IMG_SIZE": 416,
>         "BATCH_SIZE": 1,
>         "NUMBER_WORKERS": 1,
>         "CONF_THRESH": 0.5,
>         "NMS_THRESH": 0.45,
>         "MULTI_SCALE_VAL": True,
>         "FLIP_VAL": True,
>         "Visual": True
>         }
> 

Hoping for your help,Thx

**Comment by argusswift** [comment]
> Thanks a lot for your work! However, when I try to visualize heatmaps after training, I got the error:
> 
> > Traceback (most recent call last):
> > File "eval_coco.py", line 158, in 
> > heatmap=opt.heatmap).Inference()
> > File "eval_coco.py", line 117, in Inference
> > bboxes_prd = self.__evalter.get_bbox(img, v)
> > File "/root/CV/YOLOv4-pytorch-master/eval/evaluator.py", line 75, in get_bbox
> > bboxes_list.append(self.__predict(img, test_input_size, valid_scale))
> > File "/root/CV/YOLOv4-pytorch-master/eval/evaluator.py", line 97, in __predict
> > if self.showatt: _,p_d,beta = self.model(img)
> > ValueError: not enough values to unpack (expected 3, got 2)
> 
> I run the command like this:
> 
> > python eval_coco.py --gpu_id 0 --visiual output --mode det --heatmap True
> 
> Here are my config details:
> 
> > MODEL_TYPE = {"TYPE": 'YOLOv4'}  #YOLO type:YOLOv4, Mobilenet-YOLOv4 or Mobilenetv3-YOLOv4
> > CONV_TYPE = {"TYPE": 'DO_CONV'}  #conv type:DO_CONV or GENERAL
> > ATTENTION = {"TYPE": 'CBAM'}  #6
> > train
> > TRAIN = {
> > "DATA_TYPE": 'COCO',  #DATA_TYPE: VOC or COCO
> > "TRAIN_IMG_SIZE": 416,
> > "AUGMENT": True,
> > "BATCH_SIZE": 4,
> > "MULTI_SCALE_TRAIN": False,
> > "IOU_THRESHOLD_LOSS": 0.5,
> > "YOLO_EPOCHS": 50,
> > "Mobilenet_YOLO_EPOCHS": 120,
> > "NUMBER_WORKERS": 0,
> > "MOMENTUM": 0.9,
> > "WEIGHT_DECAY": 0.0005,
> > "LR_INIT": 1e-4,
> > "LR_END": 1e-5,
> > "WARMUP_EPOCHS": 0  # or None
> > }
> > VAL = {
> > "TEST_IMG_SIZE": 416,
> > "BATCH_SIZE": 1,
> > "NUMBER_WORKERS": 1,
> > "CONF_THRESH": 0.5,
> > "NMS_THRESH": 0.45,
> > "MULTI_SCALE_VAL": True,
> > "FLIP_VAL": True,
> > "Visual": True
> > }
> 
> Hoping for your help,Thx

heatmap is only used for attention.You should use this beta in global_context_block.py.
