### ISSUE TITLE
How to save the weight result of each epoch？

### ISSUE THREAD

**Issue by EternalEvan** [argusswift/YOLOv4-pytorch#90]
请问作者大大的代码能够保存每一个epoch的权重吗？还是只能保存最佳的best.pt呀，如果想保存每一个epoch的结果，可以怎么修改呢？
十分感谢！！！

**Comment by jingtianyilong** [comment]
https://github.com/argusswift/YOLOv4-pytorch/blob/c9b1093ed5ad2e5375c5f0ec9086ea121fd33d03/train.py#L101
You can somehow modify this function to achieve your goal.
https://github.com/argusswift/YOLOv4-pytorch/blob/c9b1093ed5ad2e5375c5f0ec9086ea121fd33d03/train.py#L121-L128
for example, simply remove the `if` part would work.

**Comment by EternalEvan** [comment]
> https://github.com/argusswift/YOLOv4-pytorch/blob/c9b1093ed5ad2e5375c5f0ec9086ea121fd33d03/train.py#L101
> 
> 
> You can somehow modify this function to achieve your goal.
> https://github.com/argusswift/YOLOv4-pytorch/blob/c9b1093ed5ad2e5375c5f0ec9086ea121fd33d03/train.py#L121-L128
> 
> 
> for example, simply remove the `if` part would work.

Thanks！！!
