### ISSUE TITLE
怎么正确使用last.pt

### ISSUE THREAD

**Issue by EternalEvan** [argusswift/YOLOv4-pytorch#96]
您好，我用代码训练了50个epoch之后想再继续用last.pt训练，但是出现了以下信息：
INFO:YOLOv4:  === Epoch:[  0/50],step:[ 10/22320],img_size:[416],total_loss:nan|loss_ciou:nan|loss_conf:nan|loss_cls:nan|lr:0.0000
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.
WARNING:root:NaN or Inf found in input tensor.

看到作者已经回复了一个类似的问题，说是learning rate太大了，我想再问问应该具体怎么改，是改config文件中的LR_INIT吗？

**Comment by argusswift** [comment]
> 您好，我用代码训练了50个epoch之后想再继续用last.pt训练，但是出现了以下信息：
> INFO:YOLOv4: === Epoch:[ 0/50],step:[ 10/22320],img_size:[416],total_loss:nan|loss_ciou:nan|loss_conf:nan|loss_cls:nan|lr:0.0000
> WARNING:root:NaN or Inf found in input tensor.
> WARNING:root:NaN or Inf found in input tensor.
> WARNING:root:NaN or Inf found in input tensor.
> WARNING:root:NaN or Inf found in input tensor.
> 
> 看到作者已经回复了一个类似的问题，说是learning rate太大了，我想再问问应该具体怎么改，是改config文件中的LR_INIT吗？

是的
